from django.urls import path
from .views import *
from api.mobilViewset import update_debtors, get_debtor_by_name

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/', Products.as_view(), name='product'),
    path('create_barcode/<int:id>', create_barcode, name='create_barcode'),
    path('product_filial/', ProductFilialView.as_view(), name='product_filial'),
    
    path('ltv/', LTV.as_view(), name='ltv'),
    path('get-ltv-data/', get_ltv_data, name='get_ltv_data'),
    path('filial/', Filials.as_view(), name='filial'),
    path('saler/', Saler.as_view(), name='saler'),
    path('ombor/', Ombor.as_view(), name='ombor'),
    path('omborqabul/', OmborQabul.as_view(), name='omborqabul'),
    path('omborqabul/<int:pk>/', ArticleDetailView.as_view(), name='omborqabuldetail'),
    path('omborqabul_recieve_detail/<int:id>/', omborqabul_recieve_detail, name='omborqabul_recieve_detail'),
    path('edit_receive_count/', edit_receive_count, name='edit_receive_count'),
    path('omborminus/', OmborMinus.as_view(), name='omborminus'),
    path('faktura/', Fakturas.as_view(), name='faktura'),
    # Recieve new
    path('add_recieve_item_view/',  add_recieve_item_view, name='add_recieve_item_view'),
    path('add_recieve/',  add_recieve, name='add_recieve'),
    path('delete_recieve/<int:id>/',  delete_recieve, name='delete_recieve'),
    path('delete_recieve_item/<int:id>/',  delete_recieve_item, name='delete_recieve_item'),
    path('recieve/',  Recieves.as_view(), name='recieve'),
    path('recieve_completion/<int:id>/',  recieve_completion, name='recieve_completion'),
    path('fakturatarix/', FakturaTarix.as_view(), name='fakturatarix'),
    path('warefaktura/', WareFakturas.as_view(), name='warefaktura'),
    path('warefakturatarix/', WareFakturaTarix.as_view(), name='warefakturatarix'),
    path('getfakturaitem/', GetFakturaItem, name='getfakturaitem'),
    path('datafak/', DataFak, name='datafak'),
    path('table/', Table.as_view(), name='table'),
    path('datatable/', DataTable.as_view(), name='datatable'),
    path('hodim/', Hodim.as_view(), name='hodim'),
    path('hodim_delete/<int:id>/', delete_hodim, name='hodim_delete'),
    path('debtor/', Debtors.as_view(), name='debtor'),
    path('debtor_add/', debtor_add, name='debtor_add'),
    path('tg_id_filter/', tg_id_filter, name='tg_id_filter'),
    path('debtor_edit/<int:id>', debtor_edit, name='debtor_edit'),
    path('debtor_pay/<int:id>', debtor_pay, name='debtor_pay'),
    path('debtor_give/<int:id>', debtor_give, name='debtor_give'),
    path('debtor_detail/<int:id>', debtor_detail, name='debtor_detail'),
    path('debtorhistory/', DebtorHistory, name='debtorhistory'),
    path('productinfo/<int:id>', productinfo, name='productinfo'),
    path('deliverhistory/<int:id>', deliver_detail, name='deliverhistory'),
    path('product_editing_page/', product_editing_page, name='product_editing_page'),
    path('product_editing_search/', product_editing_search, name='product_editing_search'),
    path('deliver/', Delivers.as_view(), name='deliver'),
    path('income_user_detail/', income_user_detail, name='income_user_detail'),
    path('faktura-yoqlama/', FakturaYoqlama.as_view(), name='faktura_yoqlama'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-setting/', ProfileSetting.as_view(), name='profile-setting'),
    path('sweet-alert/', SweetAlert.as_view(), name='sweet-alert'),
    path('date/', Date.as_view(), name='date'),
    path('widget/', Widget.as_view(), name='widget'),
    path('charthome/', ChartHome, name='charthome'),
    path('datahome/', DataHome, name='datahome'),
    path('dataware/', DataWare, name='dataware'),
    path('dataware_html/', DataWare_html, name='dataware_html'),
    path('getitem/', GetItem, name='getitem'),
    path('summa/', Summa, name='summa'),
    path('filialkirim/', FilialKirim, name='filialkirim'),
    path('salerkirim/', SalerKirim, name='salerkirim'),
    path('filialchiqim/', filial_chiqim_view, name='filial-chiqim'),
    
    # path('qol/', Qoldiq, name='qol'),
    path('nasiyatarix/', NasiyaTarix, name='nasiyatarix'),
    path('add_tolov/', add_tolov, name='add_tolov'),
    path('kurs-page/', kurs_page, name='kurs_page'),
    path('filialinfo/<int:id>/', filialinfo, name='filialinfo'),
    path('kassa/', kassa, name="kassa"),
    path('oylik-tolash', oylik_tolash, name='oylik-tolash'),
    path('chiqim-qilish', chiqim_qilish, name="chiqim_qilsih"),
    path('chiqim_qilish_edit', chiqim_qilish_edit, name="chiqim_qilish_edit"),
    path('kirim-qilish', kirim_qilish, name="kirim_qilish"),
    path('kirim_qilish_edit', kirim_qilish_edit, name="kirim_qilish_edit"),
    path('create_deliver', create_deliver, name="create_deliver"),
    
    path('hodim-qarz/', hodimga_qarz, name='hodim-qarz'),
    path('hodim-qarzlari/', hodim_qarzlari, name='hodim-qarzlari'),
    #api debtor change
    path('update_debtor',update_debtors),
    path('api/get_debtor_by_name',get_debtor_by_name),
    path('deliver_filter/', deliver_filter, name='deliver_filter'),
    path('add_dollar_kursi', add_dollar_kursi, name='add_dollar_kursi'),
    path('edit_deliver_history', edit_deliver_history, name='edit_deliver_history'),
    path('add_payment_comment', add_payment_comment, name='add_payment_comment'),
    path('income_status_change/', income_status_change, name='income_status_change'),
    path('null_products/', null_products, name='null_products'),
    path('all_filter/', allFilter, name='allFilter'),
    path('debtor_account', DebtorAccountView.as_view(), name='debtor_account'),
    path('shops/', ShopView.as_view(), name='shops'),
    path('shop_detail/<int:id>', shop_detail, name='shop_detail'),
     # own
    path('employee/', employee, name='employee'),
    path('payment_employee/<int:id>/', payment_employee, name='payment_employee'),
    
    path('payment_user/<int:id>/', payment_user, name='payment_user'),
    path('one_day_price/', one_day_price, name='one_day_price'),
    path('one_day_price/<int:id>/', one_day_price_add, name='one_day_price_add'),
    path('one_day_status_change/<int:id>/', one_day_status_change, name='one_day_status_change'),
    path('flex_status_change/<int:id>/', flex_status_change, name='flex_status_change'),
    path('mobile_status_change/<int:id>/', mobile_status_change, name='mobile_status_change'),
    
    
    path('accept_expanse/', accept_expanse, name='accept_expanse'),
    path('mobile_order/', mobile_order, name='mobile_order'),
    path('payment_user_mobil/<int:id>/',payment_user_mobil, name='payment_user_mobil'),
    
    path('user_detail_chiqim/<int:id>/', detail_user, name='detail_user'),
    path('detail_employee/<int:id>/', detail_employee, name='detail_employee'),
    path('detail_mobil/<int:id>/', detail_mobil, name='detail_mobil'),
    path('desktop_kassa_view/', desktop_kassa_view, name='desktop_kassa'),
    path('new_product_add/', new_product_add, name='new_product_add'),
    path('edit_recieve_item_view/', edit_recieve_item_view, name='edit_recieve_item_view'),
    path('call_center_payment/', call_center_payment, name='call_center_payment'),
    path('kassa_detail_som/', kassa_detail_som, name='kassa_detail_som'),
    path('kassa_detail_dollar/', kassa_detail_dollar, name='kassa_detail_dollar'),
    path('kassa_detail_plastik/', kassa_detail_plastik, name='kassa_detail_plastik'),
    path('kassa_detail_hisob_raqam/', kassa_detail_hisob_raqam, name='kassa_detail_hisob_raqam'),
    path('kassa_is_approved/', kassa_is_approved, name='kassa_is_approved'),
    path('change_chiqim_is_approved/<int:id>', change_chiqim_is_approved, name='change_chiqim_is_approved'),
    path('change_kirim_is_approved/<int:id>', change_kirim_is_approved, name='change_kirim_is_approved'),
    path('detail_call_center_count/<int:employee_id>', detail_call_center_count, name='detail_call_center_count'),
    path('top_products/', top_products, name='top_products'),
    path('top_debtors/', top_debtors, name='top_debtors'),
    path('detail_top_debtors/<int:id>', detail_top_debtors, name='detail_top_debtors'),
    path('top_delivers/', top_delivers, name='top_delivers'),
    # >>>>>>>>>>>>>
    path('b2c_shop/', b2c_shop_view, name='b2c_shop'),
    path('b2c_shop_add/', b2c_shop_add, name='b2c_shop_add'),
    path('b2c_shop_detail/<int:id>', b2c_shop_detail, name='b2c_shop_detail'),
    path('b2c_shop_cart_add/<int:id>', b2c_shop_cart_add, name='b2c_shop_cart_add'),
    path('b2c_shop_cart_del/<int:id>', b2c_shop_cart_del, name='b2c_shop_cart_del'),
    path('b2c_shop_cart_edit/<int:id>', b2c_shop_cart_edit, name='b2c_shop_cart_edit'),
    path('b2c_shop_finish/<int:id>', b2c_shop_finish, name='b2c_shop_finish'),
    
    #>>>>>>>>>>>>>>
    path('create_order/', create_order, name='create_order'),
    path('check_price/', check_price, name='check_price'),
    path('create_order_ajax/', create_order_ajax, name='create_order_ajax'),
    path('finish_order/<id>/', finish_order, name='finish_order'),
    path('order_detail_ajax/<order_id>/', order_detail_ajax, name='order_detail_ajax'),
    path('edit_debtor/<id>/', edit_debtor, name='edit_debtor'),
    path('refresh_debtor_debt/<id>/', refresh_debtor_debt, name='refresh_debtor_debt'),
    path('today_sales/', today_sales, name='today_sales'),
    path('analysis_costs/', analysis_costs, name='analysis_costs'),
    path('tovar_prixod/', tovar_prixod, name='tovar_prixod'),
    path('add_recieve_perexoded/', add_recieve_perexoded, name='add_recieve_perexoded'),
    path('tovar_prixod_tarix/', tovar_prixod_tarix, name='tovar_prixod_tarix'),
    path('tovar_prixod_tarix_detail/<int:id>', tovar_prixod_tarix_detail, name='tovar_prixod_tarix_detail'),
    path('money_circulation/', money_circulation, name='money_circulation'),
    path('money_circulation_add/', money_circulation_add, name='money_circulation_add'),
    path('money_circulation_edit/<int:id>', money_circulation_edit, name='money_circulation_edit'),
    path('money_circulation_delete/<int:id>', money_circulation_delete, name='money_circulation_delete'),

    path('write_off/', write_off, name='write_off'),
    path('write_off_add/', write_off_add, name='write_off_add'),
    path('write_off_item_add/', write_off_item_add, name='write_off_item_add'),
    path('write_off_item_delete/<int:id>', write_off_item_delete, name='write_off_item_delete'),
    path('write_off_delete/<int:id>', write_off_delete, name='write_off_delete'),
    path('write_off_item_edit/<int:id>', write_off_item_edit, name='write_off_item_edit'),
    path('write_off_tarix/', write_off_tarix, name='write_off_tarix'),
    path('write_off_item_detail/<int:id>', write_off_item_detail, name='write_off_item_detail'),
    path('write_off_exit/<int:id>', write_off_exit, name='write_off_exit'),
    

    path('deliver_return/', deliver_return, name='deliver_return'),
    path('deliver_return_add/', deliver_return_add, name='deliver_return_add'),
    path('deliver_return_item_add/', deliver_return_item_add, name='deliver_return_item_add'),
    path('deliver_return_tarix/', deliver_return_tarix, name='deliver_return_tarix'),
    path('deliver_return_del/<int:id>', deliver_return_del, name='deliver_return_del'),
    path('deliver_return_item_del/<int:id>', deliver_return_item_del, name='deliver_return_item_del'),
    path('deliver_return_item_edit/<int:id>', deliver_return_item_edit, name='deliver_return_item_edit'),
    path('deliver_return_item_detail/<int:id>', deliver_return_item_detail, name='deliver_return_item_detail'),
    path('deliver_return_exit/<int:id>', deliver_return_exit, name='deliver_return_exit'),

    path('create_check/<int:order_id>', create_check, name='create_check'),
    path('shop_nakladnoy/<int:order_id>', shop_nakladnoy, name='shop_nakladnoy'),
    path('fin_report/', fin_report, name='fin_report'),
    path('kassa_fin/', kassa_fin, name='kassa_fin'),
    path('exel_convert_kassa_fin/', exel_convert_kassa_fin, name='exel_convert_kassa_fin'),
    path('data_fin/', data_fin, name='data_fin'),
    path('debet_kredit_fin/', debet_kredit_fin, name='debet_kredit_fin'),
    path('cf_fin/', cf_fin, name='cf_fin'),
    path('daily_cf_fin/', daily_cf_fin, name='daily_cf_fin'),
    path('xarid_fin/', xarid_fin, name='xarid_fin'),
    path('sotuv_fin/', sotuv_fin, name='sotuv_fin'),
    path('pl_fin/', pl_fin, name='pl_fin'),
    path('balans_fin/', balans_fin, name='balans_fin'),
    path('majburiyat_fin/', majburiyat_fin, name='majburiyat_fin'),
    path('tolov_kalendar_fin/', tolov_kalendar_fin, name='tolov_kalendar_fin'),
    path('reja_tushum_fin/', reja_tushum_fin, name='reja_tushum_fin'),
    path('reja_tushum_fin_add/', reja_tushum_fin_add, name='reja_tushum_fin_add'),
    path('reja_tushum_fin_edit/<int:id>', reja_tushum_fin_edit, name='reja_tushum_fin_edit'),
    path('reja_tushum_fin_del/<int:id>', reja_tushum_fin_del, name='reja_tushum_fin_del'),
    path('reja_chiqim_fin/', reja_chiqim_fin, name='reja_chiqim_fin'),
    path('reja_chiqim_fin_add/', reja_chiqim_fin_add, name='reja_chiqim_fin_add'),
    path('reja_chiqim_fin_edit/<int:id>', reja_chiqim_fin_edit, name='reja_chiqim_fin_edit'),
    path('reja_chiqim_fin_del/<int:id>', reja_chiqim_fin_del, name='reja_chiqim_fin_del'),
    path('asosiy_vosita_fin/', asosiy_vosita_fin, name='asosiy_vosita_fin'),
    path('add_main_tool_type/', add_main_tool_type, name='add_main_tool_type'),
    path('add_main_tool/', add_main_tool, name='add_main_tool'),
    path('ajax_list_main_tool_type/', ajax_list_main_tool_type, name='ajax_list_main_tool_type'),
    path('edit_main_tool/<int:id>', edit_main_tool, name='edit_main_tool'),
    path('ombor_fin/', ombor_fin, name='ombor_fin'),
    path('b2b_shop/', b2b_shop_view, name='b2b_shop'),
    path('b2b_shop_add/', b2b_shop_add, name='b2b_shop_add'),
    path('b2b_shop_ajax/<int:product_id>', b2b_shop_ajax, name='b2b_shop_ajax'),
    path('b2b_shop_ajax_add/<int:product_id>', b2b_shop_ajax_add, name='b2b_shop_ajax_add'),
    path('b2b_shop_ajax_edit/<int:id>', b2b_shop_ajax_edit, name='b2b_shop_ajax_edit'),
    path('price_type_filter_ajax/', price_type_filter_ajax, name='price_type_filter_ajax'),
    path('nds_ajax/', nds_ajax, name='nds_ajax'),
    path('payment_shop_ajax/<int:id>', payment_shop_ajax, name='payment_shop_ajax'),
    path('add_product_list/<int:id>', add_product_list, name='add_product_list'),
    path('b2b_shop_ajax_add_one/<int:product_id>', b2b_shop_ajax_add_one, name='b2b_shop_ajax_add_one'),
    path('ajax_reja_tushum_list/<int:shop_id>', ajax_reja_tushum_list, name='ajax_reja_tushum_list'),
    path('b2b_shop_ajax_cart_delete/<int:product_id>', b2b_shop_ajax_cart_delete, name='b2b_shop_ajax_cart_delete'),
    path('nds_page/', nds_view, name='nds_page'),
    path('users_restrictions/', users_restrictions, name='users_restrictions'),
    path('users_restrictions_limit/<int:id>', users_restrictions_limit, name='users_restrictions_limit'),
    path('users_add/', users_add, name='users_add'),
    path('product_remove_quantity/<int:shop_id>', product_remove_quantity, name='product_remove_quantity'),
    path('users_change/<int:id>', users_change, name='users_change'),
    path('users_delete/<int:id>', users_delete, name='users_delete'),
    path('price_type', price_type, name='price_type'),
    path('price_type_add', price_type_add, name='price_type_add'),
    path('price_type_edit/<int:id>', price_type_edit, name='price_type_edit'),
    path('price_type_del/<int:id>', price_type_del, name='price_type_del'),

    path('product_price_type/<int:id>', product_price_type, name='product_price_type'),
    path('add_product_price_type', add_product_price_type, name='add_product_price_type'),

    path('filial_list', filial_list, name='filial_list'),
    path('filial_add', filial_add, name='filial_add'),
    path('filial_edit/<int:id>', filial_edit, name='filial_edit'),
    path('filial_del/<int:id>', filial_del, name='filial_del'),

    path('externalincomeuser', externalincomeuser, name='externalincomeuser'),
    path('externalincomeuser_add', externalincomeuser_add, name='externalincomeuser_add'),
    path('externalincomeuser_edit/<int:id>', externalincomeuser_edit, name='externalincomeuser_edit'),
    path('external_income_user_types_add', external_income_user_types_add, name='external_income_user_types_add'),
    path('income_payment/<int:id>', income_payment, name='income_payment'),
    path('income_give/<int:id>', income_give, name='income_give'),

    path('valyuta_list', valyuta_list, name='valyuta_list'),
    path('valyuta_add', valyuta_add, name='valyuta_add'),
    path('valyuta_edit/<int:id>', valyuta_edit, name='valyuta_edit'),

    path('kassa_merge', kassa_merge, name='kassa_merge'),
    path('kassa_merge_add', kassa_merge_add, name='kassa_merge_add'),
    path('kassa_merge_edit/<int:id>', kassa_merge_edit, name='kassa_merge_edit'),
    path('kassa_merge_del/<int:id>', kassa_merge_del, name='kassa_merge_del'),

    path('kassa_new_list', kassa_new_list, name='kassa_new_list'),
    path('kassa_new_add', kassa_new_add, name='kassa_new_add'),
    path('kassa_new_edit/<int:id>', kassa_new_edit, name='kassa_new_edit'),

    path('add_bonus', add_bonus, name='add_bonus'),
    path('set_start_summa', set_start_summa, name='set_start_summa'),
    path('filial_kassalar', filial_kassalar, name='filial_kassalar'),
    path('get_product_prices', get_product_prices, name='get_product_prices'),
    path('customer_debt_create/<int:id>', customer_debt_create, name='customer_debt_create'),
    path('external_income_user_debt_create/<int:id>', external_income_user_debt_create, name='external_income_user_debt_create'),
    path('externalincomeuser_detail/<int:id>', externalincomeuser_detail, name='externalincomeuser_detail'),

    path('majburiyat_chiqim_fin_add', majburiyat_chiqim_fin_add, name='majburiyat_chiqim_fin_add'),
    path('recieve-expanse/add/', add_recieve_expanse, name='add_recieve_expanse'),
    path('add_expanse_type', add_expanse_type, name='add_expanse_type'),
    path('recieve-expanse/<int:pk>/edit/', edit_recieve_expanse, name='edit_recieve_expanse'),
    path('recieve-expanse/<int:pk>/delete/', delete_recieve_expanse, name='delete_recieve_expanse'),
    path('reja_chiqim_bajarish/<int:id>/', reja_chiqim_bajarish, name='reja_chiqim_bajarish'),

    path('todays_practices', todays_practices, name='todays_practices'),

    path('reviziya', reviziya, name='reviziya'),
    path('revision_add', revision_add, name='revision_add'),
    path('list_product_price_revision', list_product_price_revision, name='list_product_price_revision'),
    path('revision_detail/<int:id>', revision_detail, name='revision_detail'),
    path('revision_item_add/<int:id>', revision_item_add, name='revision_item_add'),
    path('revision_one_item_add/<int:id>', revision_one_item_add, name='revision_one_item_add'),
    path('revision_one_item_del/<int:id>', revision_one_item_del, name='revision_one_item_del'),
    path('revison_complate/<int:id>', revison_complate, name='revison_complate'),

    path('revision_complate', revision_complate, name='revision_complate'),
    path('revision_complate_items/<int:id>', revision_complate_items, name='revision_complate_items'),

    path('measurement_type_list', measurement_type_list, name='measurement_type_list'),
    path('measurement_type_add', measurement_type_add, name='measurement_type_add'),
    path('measurement_type_edit/<int:id>', measurement_type_edit, name='measurement_type_edit'),
    path('for_pro', for_pro, name='for_pro'),
    path('mobile_order_list', mobile_order_list, name='mobile_order_list'),
    path('mobile_order_detail/<int:id>', mobile_order_detail, name='mobile_order_detail'),
    path('morder_change_status/<int:id>', morder_change_status, name='morder_change_status'),


]
