# Generated by Django 3.1.4 on 2022-09-19 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
            ],
            options={
                'verbose_name_plural': 'Mobile Banner',
            },
        ),
        migrations.CreateModel(
            name='ChangePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ChangePrice',
            },
        ),
        migrations.CreateModel(
            name='ChiqimTuri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Dollar kursi',
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=13)),
                ('phone2', models.CharField(blank=True, max_length=13, null=True)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('debt_return', models.DateField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': '7) Nasiyachilar',
            },
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=13)),
                ('phone2', models.CharField(blank=True, max_length=13, null=True)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '3.1) Deliver',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('difference_som', models.IntegerField(default=0)),
                ('difference_dollar', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': '6) Faktura',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('qarz_som', models.IntegerField(default=0)),
                ('qarz_dol', models.IntegerField(default=0)),
                ('savdo_puli_som', models.IntegerField(default=0)),
                ('savdo_puli_dol', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '2) Filial',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '3.1) Group',
            },
        ),
        migrations.CreateModel(
            name='HodimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('oylik', models.PositiveIntegerField(default=0)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filial')),
            ],
            options={
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='Kassa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('plastik', models.IntegerField(default=0)),
                ('hisob_raqam', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qancha_som', models.IntegerField(default=0)),
                ('qancha_dol', models.IntegerField(default=0)),
                ('qancha_hisob_raqamdan', models.IntegerField(default=0)),
                ('plastik', models.IntegerField(default=0)),
                ('izox', models.TextField()),
                ('qachon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Maxsulot Savatchada'), ('2', 'Sotib olingan')], default=1, max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Mobile Cart',
            },
        ),
        migrations.CreateModel(
            name='MobilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=200, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mobile Users',
            },
        ),
        migrations.CreateModel(
            name='ProductFilial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('preparer', models.CharField(default='', max_length=255)),
                ('som', models.IntegerField(default=0)),
                ('sotish_som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('sotish_dollar', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('measurement', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('litr', 'litr'), ('metr', 'metr')], default='dona', max_length=4)),
                ('min_count', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_product', to='api.filial')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
            ],
            options={
                'verbose_name_plural': '3.1) Product Filial',
            },
        ),
        migrations.CreateModel(
            name='Recieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('som', models.IntegerField(default=0)),
                ('sum_sotish_som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('sum_sotish_dollar', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('farq_dollar', models.IntegerField(default=0)),
                ('farq_som', models.IntegerField(default=0)),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
            ],
            options={
                'verbose_name_plural': '4) Recieve',
            },
        ),
        migrations.CreateModel(
            name='ReturnProductToDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name_plural': 'Return Product To Deliver',
            },
        ),
        migrations.CreateModel(
            name='Telegramid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yalpi_savdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filial')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productfilial')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('staff', models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'saler'), (4, 'warehouse')], default=3)),
                ('active', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1) User',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('naqd_som', models.IntegerField(default=0)),
                ('naqd_dollar', models.IntegerField(default=0)),
                ('plastik', models.FloatField(default=0)),
                ('nasiya_som', models.IntegerField(default=0)),
                ('nasiya_dollar', models.IntegerField(default=0)),
                ('transfer', models.IntegerField(default=0)),
                ('skidka_dollar', models.IntegerField(default=0)),
                ('skidka_som', models.IntegerField(default=0)),
                ('debt_return', models.DateField(blank=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('saler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
            ],
            options={
                'verbose_name_plural': '5) Shop',
            },
        ),
        migrations.CreateModel(
            name='ReturnProductToDeliverItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('returnproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.returnproducttodeliver')),
            ],
            options={
                'verbose_name_plural': 'Return Product To Deliver Item',
            },
        ),
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quan', models.FloatField(default=0)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': 'Return Product',
            },
        ),
        migrations.CreateModel(
            name='RecieveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField(default=0)),
                ('sotish_som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('sotish_dollar', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('recieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recieve')),
            ],
            options={
                'verbose_name_plural': '4.1) RecieveItem',
            },
        ),
        migrations.CreateModel(
            name='Pereotsenka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name_plural': 'Pereotsenka',
            },
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField()),
                ('dollar', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_pay', to='api.filial')),
            ],
            options={
                'verbose_name_plural': '9) Tolov Tarixi',
            },
        ),
        migrations.CreateModel(
            name='OylikTolov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pul', models.PositiveIntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hodimmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MyOwnToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.mobiluser', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Mobile Token',
                'verbose_name_plural': 'Mobile Tokens',
            },
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='api.MCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser')),
            ],
            options={
                'verbose_name_plural': 'Mobile order',
            },
        ),
        migrations.AddField(
            model_name='mcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial'),
        ),
        migrations.AddField(
            model_name='mcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
        migrations.CreateModel(
            name='Kamomad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valyuta', models.CharField(max_length=25)),
                ('difference_sum', models.IntegerField(default=0)),
                ('difference_dollar', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
        ),
        migrations.CreateModel(
            name='HodimQarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qancha_som', models.PositiveIntegerField(default=0)),
                ('qancha_dol', models.PositiveIntegerField(default=0)),
                ('qaytargani_som', models.IntegerField(default=0)),
                ('qaytargani_dol', models.IntegerField(default=0)),
                ('izox', models.TextField(blank=True, null=True)),
                ('qaytargandagi_izox', models.TextField(blank=True, null=True)),
                ('tolandi', models.BooleanField(default=False)),
                ('qachon', models.DateTimeField(auto_now_add=True)),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hodimmodel')),
            ],
            options={
                'verbose_name_plural': 'Hodimlar qarzi',
            },
        ),
        migrations.CreateModel(
            name='FakturaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body_som', models.IntegerField(default=0)),
                ('body_dollar', models.IntegerField(default=0)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=255)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.faktura')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groups')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': '6.1) FakturaItem',
            },
        ),
        migrations.AddField(
            model_name='faktura',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.CreateModel(
            name='DeliverPayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField()),
                ('dollar', models.IntegerField()),
                ('turi', models.CharField(choices=[('Naqd', 'Naqd'), ('Plastik', 'Plastik'), ("Pul o'tkazish", "Pul o'tkazish")], default='Naqd', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
            ],
            options={
                'verbose_name_plural': 'Deliver Tolov Tarixi',
            },
        ),
        migrations.CreateModel(
            name='DebtDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
            ],
            options={
                'verbose_name_plural': 'Deliver Qarzi',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('return_date', models.DateField()),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
            options={
                'verbose_name_plural': 'Qarz Tarixi',
            },
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qancha_som', models.IntegerField(default=0)),
                ('qancha_dol', models.IntegerField(default=0)),
                ('qancha_hisob_raqamdan', models.IntegerField(default=0)),
                ('izox', models.TextField()),
                ('qachon', models.DateTimeField(auto_now_add=True)),
                ('qayerga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chiqimturi')),
            ],
        ),
        migrations.CreateModel(
            name='ChangePriceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_som', models.IntegerField(default=0)),
                ('old_dollar', models.IntegerField(default=0)),
                ('new_som', models.IntegerField(default=0)),
                ('new_dollar', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('changeprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.changeprice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': 'ChangePriceIten',
            },
        ),
        migrations.AddField(
            model_name='changeprice',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.CreateModel(
            name='CartDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('given_quan', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('return_quan', models.FloatField(default=0)),
                ('return_sum', models.IntegerField(default=0)),
                ('debt_quan', models.FloatField(default=0)),
                ('debt_sum', models.FloatField(default=0)),
                ('difference', models.FloatField(default=0)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
            options={
                'verbose_name_plural': 'CartDebt',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
            options={
                'verbose_name_plural': '5.1) Cart',
            },
        ),
    ]
