# Generated by Django 3.1.4 on 2022-09-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ManyToManyField(related_name='products1', to='api.Deliver'),
        ),
    ]
