# Generated by Django 3.1.4 on 2022-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productfilial_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpayhistory',
            name='kurs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
