# Generated by Django 3.1.4 on 2022-12-04 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_deliverpayhistory_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtdeliver',
            name='deliver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtdeliver', to='api.deliver'),
        ),
        migrations.AlterField(
            model_name='deliverpayhistory',
            name='deliver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverpayhistory', to='api.deliver'),
        ),
        migrations.AlterField(
            model_name='recieveitem',
            name='recieve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiveitem', to='api.recieve'),
        ),
        migrations.CreateModel(
            name='DeliverPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('received_total', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('gave_total', models.FloatField(default=0)),
                ('comment', models.TextField()),
                ('left', models.FloatField(default=0)),
                ('check_comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
