# Generated by Django 3.1.4 on 2022-12-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20221204_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpayments',
            name='check_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverpayments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverpayments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
