# Generated by Django 3.1.4 on 2022-12-07 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20221204_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverpayments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='deliverpayments',
            name='gave_total',
        ),
        migrations.RemoveField(
            model_name='deliverpayments',
            name='left',
        ),
        migrations.RemoveField(
            model_name='deliverpayments',
            name='received_total',
        ),
        migrations.RemoveField(
            model_name='deliverpayments',
            name='total',
        ),
        migrations.RemoveField(
            model_name='deliverpayments',
            name='user',
        ),
        migrations.AddField(
            model_name='deliverpayments',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.deliver'),
        ),
        migrations.CreateModel(
            name='DeliverPaymentsAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_total', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('gave_total', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliverpayments',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='deliverpayments', to='api.DeliverPaymentsAll'),
        ),
    ]
