# Generated by Django 3.1.4 on 2022-12-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221207_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='gave_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='left',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='received_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
