# Generated by Django 3.1.4 on 2022-12-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221211_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='qancha_dol_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='qancha_hisob_raqamdan_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='qancha_som_eski',
            field=models.IntegerField(default=0),
        ),
    ]
