# Generated by Django 3.1.4 on 2022-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221214_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='plastik_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='qancha_dol_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='qancha_hisob_raqamdan_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='qancha_som_eski',
            field=models.IntegerField(default=0),
        ),
    ]
