# Generated by Django 3.1.4 on 2022-12-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221214_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='qayerga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chiqimturi'),
        ),
    ]
