# Generated by Django 3.1.4 on 2022-12-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_kirim_qayerga'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='kassa_dol_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_dol_yangi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_hisob_raqam_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_hisob_raqam_yangi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_plastik_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_plastik_yangi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_som_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_som_yangi',
            field=models.IntegerField(default=0),
        ),
    ]
