# Generated by Django 3.1.4 on 2022-12-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20221214_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_dol_eski',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_dol_yangi',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_hisob_raqam_eski',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_hisob_raqam_yangi',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_plastik_eski',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_plastik_yangi',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_som_eski',
        ),
        migrations.RemoveField(
            model_name='kirim',
            name='kassa_som_yangi',
        ),
    ]
