# Generated by Django 3.1.4 on 2022-12-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221214_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='qayerga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.chiqimturi'),
        ),
    ]
