# Generated by Django 3.1.4 on 2022-12-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20221214_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='kassa_plastik_eski',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='kassa_plastik_yangi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='plastik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='plastik_eski',
            field=models.IntegerField(default=0),
        ),
    ]
