# Generated by Django 3.1.4 on 2022-12-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20221214_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.deliver'),
        ),
    ]
