# Generated by Django 3.1.4 on 2023-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_chiqim_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
