# Generated by Django 3.1.4 on 2023-01-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20230106_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='click',
        ),
    ]
