# Generated by Django 3.1.4 on 2023-01-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_cart_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='click',
        ),
    ]
