# Generated by Django 3.1.4 on 2023-01-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_shop_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
