# Generated by Django 3.1.4 on 2023-01-25 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20230125_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtdeliver',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
