# Generated by Django 3.1.4 on 2023-01-25 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230125_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverpaymentsall',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
