# Generated by Django 3.1.4 on 2023-02-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20230126_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Filial chiqim turi',
                'verbose_name_plural': 'Filial chiqim turlari',
            },
        ),
        migrations.CreateModel(
            name='FilialExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=255)),
                ('total_sum', models.FloatField()),
                ('currency', models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar'), ('carta', 'carta'), ('utkazma', 'utkazma')], default="so'm", max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filialexpensecategory')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
            options={
                'verbose_name': 'Filial chiqim',
                'verbose_name_plural': 'Filial chiqimlar',
            },
        ),
        migrations.CreateModel(
            name='CashboxReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.FloatField()),
                ('total_dollar', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(choices=[("so'm", "so'm"), ('dollar', 'dollar'), ('carta', 'carta'), ('utkazma', 'utkazma')], default="so'm", max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='waiting', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
            ],
        ),
    ]
