# Generated by Django 3.1.4 on 2023-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_cashboxreceive_filialexpense_filialexpensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxreceive',
            name='kassa_dollar_new',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashboxreceive',
            name='kassa_dollar_old',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashboxreceive',
            name='kassa_sum_new',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashboxreceive',
            name='kassa_sum_old',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filialexpense',
            name='kassa_sum_new',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filialexpense',
            name='kassa_sum_old',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashboxreceive',
            name='total_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
