# Generated by Django 3.1.4 on 2023-02-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20230209_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filialexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filialexpense',
            name='filial',
        ),
        migrations.DeleteModel(
            name='CashboxReceive',
        ),
        migrations.DeleteModel(
            name='FilialExpense',
        ),
        migrations.DeleteModel(
            name='FilialExpenseCategory',
        ),
    ]
