# Generated by Django 3.1.4 on 2023-02-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cashboxreceive_filialexpense_filialexpensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxreceive',
            name='director_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.productfilial'),
        ),
    ]
