# Generated by Django 3.1.4 on 2023-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20230226_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='check_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
