# Generated by Django 3.1.4 on 2023-04-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_deliverpaymentsall_check_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.debtor'),
        ),
    ]
