# Generated by Django 3.1.4 on 2023-04-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_shop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.shop'),
        ),
    ]
