# Generated by Django 3.1.4 on 2023-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20230417_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='distributsiya',
            field=models.IntegerField(default=0),
        ),
    ]
