# Generated by Django 3.1.4 on 2023-06-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_productfilial_distributsiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
