# Generated by Django 3.1.4 on 2023-06-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productcategory'),
        ),
    ]
