# Generated by Django 3.1.4 on 2023-06-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20230612_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_categories/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_categories/'),
        ),
    ]
