# Generated by Django 3.1.4 on 2023-06-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20230617_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
