# Generated by Django 3.1.4 on 2023-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_cart_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcart',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
