# Generated by Django 3.1.4 on 2023-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_mcart_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='SekretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='return_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
