# Generated by Django 3.1.4 on 2023-07-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20230703_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='return_left',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
