# Generated by Django 3.1.4 on 2023-07-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_deliverpaymentsall_return_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverpaymentsall',
            name='return_left',
        ),
        migrations.RemoveField(
            model_name='deliverpaymentsall',
            name='total',
        ),
    ]
