# Generated by Django 3.1.4 on 2023-08-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20230703_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='debtor',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='debtor_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'saler'), (4, 'warehouse'), (5, 'agent')], default=3),
        ),
        migrations.CreateModel(
            name='Teritory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.AddField(
            model_name='debtor',
            name='teritory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.teritory'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.debtortype'),
        ),
    ]
