# Generated by Django 3.1.4 on 2023-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20230811_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='lan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='debtor',
            name='lat',
            field=models.FloatField(default=0),
        ),
    ]
