# Generated by Django 3.1.4 on 2023-08-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20230813_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='teritory',
            options={'verbose_name_plural': 'Hududlar'},
        ),
    ]
