# Generated by Django 3.1.4 on 2023-08-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20230821_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilial',
            name='barcode',
        ),
    ]
