# Generated by Django 3.1.4 on 2023-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_productfilial_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='barcode',
            field=models.CharField(default='<function now at 0x7f647b1dff70>', max_length=255),
            preserve_default=False,
        ),
    ]
