# Generated by Django 3.1.4 on 2023-08-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_productfilial_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='api.mobiluser'),
        ),
    ]
