# Generated by Django 3.1.4 on 2023-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20230828_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='inn',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
