# Generated by Django 3.1.4 on 2023-08-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20230828_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
