# Generated by Django 3.1.4 on 2023-08-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20230829_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcart',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
    ]
