# Generated by Django 3.1.4 on 2023-09-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_mcart_debtor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Narx turi',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pricetype')),
            ],
            options={
                'verbose_name_plural': 'Maxsulot narx turi',
            },
        ),
    ]
