# Generated by Django 3.1.4 on 2023-10-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_pricetype_productpricetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcart',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
