# Generated by Django 3.1.4 on 2023-10-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_mcart_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filial_pay', to='api.filial'),
        ),
    ]
