# Generated by Django 3.1.4 on 2023-10-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20231030_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.IntegerField()),
                ('dollar', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
            ],
        ),
    ]
