# Generated by Django 3.1.4 on 2023-10-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_paychecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecker',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
    ]
