# Generated by Django 3.1.4 on 2023-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_paychecker_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecker',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
