# Generated by Django 3.1.4 on 2023-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_paychecker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecker',
            name='comment',
            field=models.TextField(blank=True, default='Izoh yo`q', null=True),
        ),
        migrations.AddField(
            model_name='paychecker',
            name='currency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='comment',
            field=models.TextField(blank=True, default='Izoh yo`q', null=True),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='currency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
