# Generated by Django 3.1.4 on 2023-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20231031_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricetype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
