# Generated by Django 3.1.4 on 2023-11-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20231106_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
