# Generated by Django 3.1.4 on 2023-11-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_morder_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
    ]
