# Generated by Django 3.1.4 on 2023-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20231129_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveitem',
            name='old_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
