# Generated by Django 3.1.4 on 2023-12-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_recieveitem_old_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveitem',
            name='old_sotish_som',
            field=models.IntegerField(default=0),
        ),
    ]
