# Generated by Django 3.1.4 on 2023-12-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_recieveitem_old_sotish_som'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveitem',
            name='old_prices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
