# Generated by Django 3.1.4 on 2023-12-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_recieveitem_old_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetype',
            options={'ordering': ['id'], 'verbose_name_plural': 'Narx turi'},
        ),
        migrations.AddField(
            model_name='returnproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
    ]
