# Generated by Django 3.1.4 on 2023-12-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20231210_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnproduct',
            name='shop',
        ),
        migrations.AddField(
            model_name='returnproduct',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.debtor'),
        ),
    ]
