# Generated by Django 3.1.4 on 2023-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20231210_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='desktop_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
