# Generated by Django 3.1.4 on 2023-12-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_shop_desktop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='desktop_id',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
