# Generated by Django 3.1.4 on 2023-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20231215_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='desktop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
