# Generated by Django 3.1.4 on 2023-12-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_payhistory_desktop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='deliverpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverpaymentsall'),
        ),
    ]
