# Generated by Django 3.1.4 on 2023-12-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_chiqim_deliverpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpayments',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverpayments', to='api.deliver'),
        ),
    ]
