# Generated by Django 3.1.4 on 2023-12-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20231226_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverpaymentsall', to='api.deliver'),
        ),
    ]
