# Generated by Django 3.1.4 on 2023-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_deliverpaymentsall_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='desktop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
