# Generated by Django 3.1.4 on 2024-02-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_debtor_desktop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_wage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debtor_shops', to='api.debtor'),
        ),
    ]
