# Generated by Django 3.1.4 on 2024-02-12 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20240212_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayPice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.FloatField(default=1)),
                ('one_day_price', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sana', models.DateField(null=True)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
