# Generated by Django 3.1.4 on 2024-02-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_fixprice_flexprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixprice',
            old_name='date',
            new_name='sana',
        ),
        migrations.RenameField(
            model_name='flexprice',
            old_name='date',
            new_name='sana',
        ),
        migrations.RemoveField(
            model_name='flexprice',
            name='cart',
        ),
    ]
