# Generated by Django 3.1.4 on 2024-02-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20240212_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexprice',
            name='sana',
        ),
    ]
