# Generated by Django 3.1.4 on 2024-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_flexprice_sana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedaypice',
            name='one_day_price',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fix_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='one_day_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
