# Generated by Django 3.1.4 on 2024-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20240212_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaypice',
            name='one_day_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
