# Generated by Django 3.1.4 on 2024-02-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_onedaypice_one_day_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fix_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='one_day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
