# Generated by Django 3.1.4 on 2024-02-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20240212_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixPrice',
        ),
    ]
