# Generated by Django 3.1.4 on 2024-02-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_delete_fixprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexprice',
            name='sana',
            field=models.DateField(null=True),
        ),
    ]
