# Generated by Django 3.1.4 on 2024-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_flexprice_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flex_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
