# Generated by Django 3.1.4 on 2024-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_userprofile_flex_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexprice',
            name='flex',
        ),
        migrations.AddField(
            model_name='flexprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
