# Generated by Django 3.1.4 on 2024-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20240212_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexprice',
            name='price',
        ),
        migrations.AddField(
            model_name='flexprice',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
