# Generated by Django 3.1.4 on 2024-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20240212_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexprice',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
