# Generated by Django 3.1.4 on 2024-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20240212_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexprice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
