# Generated by Django 3.1.4 on 2024-02-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_flexprice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fix_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flex_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
