# Generated by Django 3.1.4 on 2024-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_mobilpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilpayment',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
