# Generated by Django 3.1.4 on 2024-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_mobilpayment_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiluser',
            name='fix_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='mobiluser',
            name='flex_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
