# Generated by Django 3.1.4 on 2024-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20240213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexprice',
            name='fix_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
