# Generated by Django 3.1.4 on 2024-02-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_flexprice_fix_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexprice',
            old_name='fix_price',
            new_name='flex_price',
        ),
    ]
