# Generated by Django 3.1.4 on 2024-02-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20240213_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilpayment',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='morder',
            name='products',
            field=models.ManyToManyField(related_name='morders', to='api.MCart'),
        ),
    ]
