# Generated by Django 3.1.4 on 2024-02-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20240213_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayemntMobilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('m_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser')),
            ],
        ),
    ]
