# Generated by Django 3.1.4 on 2024-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_payemntmobiluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilpayment',
            name='flex_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
