# Generated by Django 3.1.4 on 2024-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20240214_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilpayment',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
