# Generated by Django 3.1.4 on 2024-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20240214_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='transfer',
            field=models.IntegerField(default=0),
        ),
    ]
