# Generated by Django 3.1.4 on 2024-02-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20240214_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='transfer',
        ),
    ]
