# Generated by Django 3.1.4 on 2024-02-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_remove_payhistory_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
