# Generated by Django 3.1.4 on 2024-02-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_chiqim_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='mobil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
    ]
