# Generated by Django 3.1.4 on 2024-02-14 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_chiqim_mobil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaypice',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mobilpayment',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
