# Generated by Django 3.1.4 on 2024-02-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20240214_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='one_day_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
