# Generated by Django 3.1.4 on 2024-02-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_auto_20240214_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentuserprofile',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='PayemntMobilUser',
        ),
        migrations.DeleteModel(
            name='PaymentUserProfile',
        ),
    ]
