# Generated by Django 3.1.4 on 2024-02-21 15:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20240215_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 15, 1, 30, 645653)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
