# Generated by Django 3.1.4 on 2024-02-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20240221_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='lacation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 16, 30, 4, 433462)),
        ),
    ]
