# Generated by Django 3.1.4 on 2024-02-22 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_auto_20240221_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 13, 30, 35, 886716)),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='dollar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='som',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
