# Generated by Django 3.1.4 on 2024-02-22 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20240222_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='lacation',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 18, 16, 8, 897852)),
        ),
    ]
