# Generated by Django 3.1.4 on 2024-02-23 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20240222_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='paychecker',
            name='bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paychecker',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='dollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='som',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 11, 32, 44, 536398)),
        ),
    ]
