# Generated by Django 3.1.4 on 2024-02-23 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20240223_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paychecker',
            name='bank',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='click',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='dollar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paychecker',
            name='som',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 11, 37, 27, 61036)),
        ),
    ]
