# Generated by Django 3.1.4 on 2024-02-23 14:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20240223_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilpayment',
            name='sana',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 14, 29, 12, 140986)),
        ),
    ]
