# Generated by Django 3.1.4 on 2024-02-24 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20240224_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiluser',
            name='price_and',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Oylik ishchi kelmaganda ayriladigon pul'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 17, 42, 28, 463082)),
        ),
    ]
