# Generated by Django 3.1.4 on 2024-02-24 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_auto_20240224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 17, 44, 50, 558196)),
        ),
    ]
