# Generated by Django 3.1.4 on 2024-03-06 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20240224_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='after',
            field=models.IntegerField(default=0, verbose_name='Flex limit'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 13, 24, 22, 516329)),
        ),
    ]
