# Generated by Django 3.1.4 on 2024-03-06 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_auto_20240306_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiluser',
            name='after',
            field=models.IntegerField(default=0, verbose_name='Flex limit'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 14, 18, 41, 453143)),
        ),
    ]
