# Generated by Django 3.1.4 on 2024-03-11 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20240306_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexprice',
            name='summa_fex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 15, 28, 53, 575870)),
        ),
    ]
