# Generated by Django 3.1.4 on 2024-03-13 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_auto_20240312_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopKassa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('kassa_name', models.CharField(max_length=255)),
                ('operation_name', models.CharField(max_length=255)),
                ('remainder_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('new_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('desktop_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 13, 1, 29, 185251)),
        ),
    ]
