# Generated by Django 3.1.4 on 2024-03-13 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20240313_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 13, 2, 24, 495127)),
        ),
    ]
