# Generated by Django 3.1.4 on 2024-03-13 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20240313_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktopkassa',
            old_name='new_price',
            new_name='qoldik',
        ),
        migrations.RenameField(
            model_name='desktopkassa',
            old_name='remainder_price',
            new_name='yangi_qoldik',
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 13, 19, 39, 460746)),
        ),
    ]
