# Generated by Django 3.1.4 on 2024-03-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20240313_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 9, 22, 3, 113070)),
        ),
    ]
