# Generated by Django 3.1.4 on 2024-03-16 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_auto_20240315_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopkassa',
            name='debtor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 11, 38, 17, 769335)),
        ),
    ]
