# Generated by Django 3.1.4 on 2024-03-18 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_auto_20240318_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 55, 42, 451960)),
        ),
    ]
