# Generated by Django 3.1.4 on 2024-03-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_auto_20240318_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqimturi',
            name='kunlik',
            field=models.BooleanField(default=False, verbose_name='kozda tutilgan harajat'),
        ),
        migrations.AddField(
            model_name='filialexpensecategory',
            name='kunlik',
            field=models.BooleanField(default=False, verbose_name='kozda tutilgan harajat'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 19, 6, 51, 401708)),
        ),
    ]
