# Generated by Django 3.1.4 on 2024-03-21 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_auto_20240318_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopkassa',
            name='kassa_turi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 13, 37, 53, 486411)),
        ),
    ]
