# Generated by Django 3.1.4 on 2024-03-22 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_auto_20240321_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopkassa',
            name='kassa_turi',
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 11, 13, 3, 114937)),
        ),
    ]
