# Generated by Django 3.1.4 on 2024-04-06 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_auto_20240406_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 19, 37, 34, 751235)),
        ),
    ]
