# Generated by Django 3.1.4 on 2024-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0148_auto_20240409_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='bring_price',
            field=models.FloatField(default=0),
        ),
    ]
