# Generated by Django 3.1.4 on 2024-05-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_cart_bring_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDaySumEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fix', models.FloatField(default=0)),
                ('flex', models.FloatField(default=0)),
                ('pay', models.FloatField(default=0)),
                ('rest', models.FloatField(default=0)),
                ('izox', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
    ]
