# Generated by Django 3.1.4 on 2024-05-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0150_alldaysumemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldaysumemployee',
            name='pay',
            field=models.FloatField(default=0, verbose_name='Tolandi'),
        ),
        migrations.AlterField(
            model_name='alldaysumemployee',
            name='rest',
            field=models.FloatField(default=0, verbose_name='Qoldik'),
        ),
    ]
