# Generated by Django 3.1.4 on 2024-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20240530_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysumemployee',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
