# Generated by Django 3.1.4 on 2024-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_alldaysumemployee_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysumemployee',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
    ]
