# Generated by Django 3.1.4 on 2024-10-31 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0153_alldaysumemployee_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='call_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_center_orders', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='saler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_orders', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'saler'), (4, 'warehouse'), (5, 'agent'), (6, 'agent')], default=3),
        ),
    ]
