# Generated by Django 3.1.4 on 2024-10-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0154_auto_20241031_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='staff',
            field=models.IntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'saler'), (4, 'warehouse'), (5, 'agent'), (6, 'call_center')], default=3),
        ),
    ]
