# Generated by Django 3.1.4 on 2024-11-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0155_auto_20241031_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kirim',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productpricetype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='api.productfilial'),
        ),
    ]
