# Generated by Django 3.1.4 on 2024-12-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_auto_20241122_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='call_center',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
