# Generated by Django 3.1.4 on 2024-12-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_auto_20241203_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqimturi',
            name='for_employee',
            field=models.BooleanField(default=False),
        ),
    ]
