# Generated by Django 3.1.4 on 2024-12-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_chiqimturi_for_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldaysumemployee',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
