# Generated by Django 3.1.4 on 2024-12-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0161_desctopchiqim'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopChiqim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qancha_som', models.IntegerField(default=0)),
                ('qancha_dol', models.IntegerField(default=0)),
                ('plastik', models.IntegerField(default=0)),
                ('qancha_hisob_raqamdan', models.IntegerField(default=0)),
                ('izox', models.TextField()),
                ('qachon', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
                ('deliverpayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverpaymentsall')),
                ('mobil_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser')),
                ('qayerga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.chiqimturi')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='DesctopChiqim',
        ),
    ]
