# Generated by Django 3.1.4 on 2024-12-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_auto_20241206_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopchiqim',
            name='deliverpayment',
        ),
        migrations.RemoveField(
            model_name='desktopchiqim',
            name='mobil_user',
        ),
        migrations.AlterField(
            model_name='desktopchiqim',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.deliver'),
        ),
    ]
