# Generated by Django 3.1.4 on 2024-12-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_auto_20241206_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktopchiqim',
            name='deliver',
        ),
        migrations.AlterField(
            model_name='desktopchiqim',
            name='izox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
