# Generated by Django 3.1.4 on 2024-12-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0164_auto_20241206_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopchiqim',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
