# Generated by Django 3.1.4 on 2025-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_desktopchiqim_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='after_cart',
            field=models.FloatField(default=0),
        ),
    ]
