# Generated by Django 3.1.4 on 2025-01-13 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_cart_after_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilialDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('obyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
            ],
        ),
        migrations.CreateModel(
            name='KassaDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('obyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kassa')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverFilialDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('obyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
            ],
        ),
        migrations.CreateModel(
            name='DebtorDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest', models.FloatField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('obyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
            ],
        ),
    ]
