# Generated by Django 3.1.4 on 2025-01-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_debtordaily_deliverfilialdaily_kassadaily_productfilialdaily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kassadaily',
            name='rest',
        ),
        migrations.AddField(
            model_name='kassadaily',
            name='dollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kassadaily',
            name='hisob_raqam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kassadaily',
            name='plastik',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kassadaily',
            name='som',
            field=models.IntegerField(default=0),
        ),
    ]
