# Generated by Django 3.1.4 on 2025-01-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_auto_20250113_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliverFilialDaily',
            new_name='DeliverDaily',
        ),
    ]
