# Generated by Django 3.1.4 on 2025-02-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_auto_20250207_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viloyat',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
