# Generated by Django 3.1.4 on 2025-02-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_auto_20250207_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilial',
            name='deliver',
        ),
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ManyToManyField(blank=True, related_name='products1', to='api.Deliver'),
        ),
    ]
