# Generated by Django 3.1.4 on 2025-02-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_auto_20250207_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilial',
            name='deliver',
        ),
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver'),
        ),
    ]
