# Generated by Django 3.1.4 on 2025-02-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_auto_20250207_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfilial',
            old_name='deliver',
            new_name='deliver1',
        ),
    ]
