# Generated by Django 3.1.4 on 2025-02-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0174_auto_20250209_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ManyToManyField(blank=True, related_name='products1', to='api.Deliver'),
        ),
    ]
