# Generated by Django 3.1.4 on 2025-02-10 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0175_productfilial_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
