# Generated by Django 3.1.4 on 2025-02-14 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0176_auto_20250210_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='start_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
