# Generated by Django 3.1.4 on 2025-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0177_auto_20250214_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
