# Generated by Django 3.1.4 on 2025-02-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0178_productfilial_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='kurs',
            field=models.IntegerField(default=0),
        ),
    ]
