# Generated by Django 3.1.4 on 2025-02-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0179_shop_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_dollar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_som',
            field=models.BooleanField(default=True),
        ),
    ]
