# Generated by Django 3.1.4 on 2025-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_auto_20250219_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode_product/'),
        ),
    ]
