# Generated by Django 3.1.4 on 2025-02-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_auto_20250221_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_without_skidka',
            field=models.IntegerField(default=0),
        ),
    ]
