# Generated by Django 3.1.4 on 2025-02-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_cart_price_without_skidka'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
    ]
