# Generated by Django 3.1.4 on 2025-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0183_payhistory_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='plastik',
            field=models.IntegerField(default=0),
        ),
    ]
