# Generated by Django 3.1.4 on 2025-02-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0184_payhistory_plastik'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
