# Generated by Django 3.1.4 on 2025-02-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0185_shop_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='dollar_after',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='som_after',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='dollar_after',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='som_after',
            field=models.FloatField(default=0),
        ),
    ]
