# Generated by Django 3.1.4 on 2025-02-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_auto_20250224_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='payhistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payhistory'),
        ),
    ]
