# Generated by Django 3.1.4 on 2025-02-25 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_kirim_payhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 16, 6, 38, 507294)),
        ),
        migrations.AddField(
            model_name='debtor',
            name='start_dollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='debtor',
            name='start_som',
            field=models.IntegerField(default=0),
        ),
    ]
