# Generated by Django 3.1.4 on 2025-03-04 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_auto_20250225_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='is_prexoded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 11, 34, 55, 887411)),
        ),
    ]
