# Generated by Django 3.1.4 on 2025-03-04 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0190_auto_20250304_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 15, 44, 13, 916952)),
        ),
    ]
