# Generated by Django 3.1.4 on 2025-03-04 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_auto_20250304_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycirculation',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 15, 46, 32, 179816)),
        ),
    ]
