# Generated by Django 3.1.4 on 2025-03-04 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_auto_20250304_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 15, 58, 21, 671766)),
        ),
    ]
