# Generated by Django 3.1.4 on 2025-03-05 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_auto_20250304_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 9, 21, 34, 313932)),
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.writeoff')),
            ],
        ),
    ]
