# Generated by Django 3.1.4 on 2025-03-05 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_auto_20250305_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 9, 50, 46, 928327)),
        ),
        migrations.AlterField(
            model_name='writeoffitem',
            name='write_off',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeoffitem', to='api.writeoff'),
        ),
    ]
