# Generated by Django 3.1.4 on 2025-03-05 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_auto_20250305_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 9, 54, 20, 383036)),
        ),
    ]
