# Generated by Django 3.1.4 on 2025-03-10 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_auto_20250305_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycirculation',
            name='chiqim_turi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chiqimturi'),
        ),
        migrations.AddField(
            model_name='moneycirculation',
            name='manba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moneycirculation',
            name='manba_turi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moneycirculation',
            name='sub_manba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 11, 49, 36, 467043)),
        ),
        migrations.AlterField(
            model_name='moneycirculation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
