# Generated by Django 3.1.4 on 2025-03-15 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_auto_20250310_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 11, 35, 14, 62350)),
        ),
    ]
