# Generated by Django 3.1.4 on 2025-03-17 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_auto_20250315_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='payhistory',
            name='deliver_all_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverpaymentsall'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 15, 34, 24, 711392)),
        ),
    ]
