# Generated by Django 3.1.4 on 2025-03-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_auto_20250317_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valyuta',
            old_name='phone',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 15, 34, 48, 46083)),
        ),
    ]
