# Generated by Django 3.1.4 on 2025-03-17 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_auto_20250317_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepriceitem',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='debt',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='debtdeliver',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='deliver',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='deliverpayhistory',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='fakturaitem',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='filial',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='hodimqarz',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='kassa',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='kassadaily',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='paychecker',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='pereotsenka',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='recieve',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='recieveitem',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='returnproduct',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='returnproducttodeliver',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='returnproducttodeliveritem',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='shop',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 15, 39, 1, 206407)),
        ),
    ]
