# Generated by Django 3.1.4 on 2025-03-18 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_auto_20250317_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpayhistory',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='deliver_pay_History',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverpayhistory'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 9, 48, 29, 61878)),
        ),
    ]
