# Generated by Django 3.1.4 on 2025-03-22 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_auto_20250318_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='b2c',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 9, 53, 16, 415950)),
        ),
    ]
