# Generated by Django 3.1.4 on 2025-03-22 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_auto_20250322_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
        migrations.AddField(
            model_name='shop',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contract'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 37, 47, 905470)),
        ),
    ]
