# Generated by Django 3.1.4 on 2025-03-24 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_auto_20250324_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 14, 0, 49, 368685)),
        ),
    ]
