# Generated by Django 3.1.4 on 2025-03-27 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0208_auto_20250324_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perecent', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 15, 36, 55, 135184)),
        ),
    ]
