# Generated by Django 3.1.4 on 2025-03-28 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0209_auto_20250327_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 33, 32, 21664)),
        ),
    ]
