# Generated by Django 3.1.4 on 2025-03-28 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_auto_20250328_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 14, 0, 32, 386900)),
        ),
    ]
