# Generated by Django 3.1.4 on 2025-03-28 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_auto_20250328_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 20, 45, 23, 328628)),
        ),
    ]
