# Generated by Django 3.1.4 on 2025-03-29 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_auto_20250328_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 11, 44, 8, 467512)),
        ),
        migrations.AlterField(
            model_name='nds',
            name='perecent',
            field=models.IntegerField(default=0),
        ),
    ]
