# Generated by Django 3.1.4 on 2025-04-03 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0218_auto_20250329_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 9, 56, 12, 854395)),
        ),
    ]
