# Generated by Django 3.1.4 on 2025-04-04 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_auto_20250403_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 16, 37, 33, 213137)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
