# Generated by Django 3.1.4 on 2025-04-04 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0220_auto_20250404_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_savdo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 20, 36, 31, 720060)),
        ),
    ]
