# Generated by Django 3.1.4 on 2025-04-05 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_auto_20250404_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricetype'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 12, 23, 45, 363791)),
        ),
    ]
