# Generated by Django 3.1.4 on 2025-04-05 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_auto_20250405_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='is_dollar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 12, 39, 41, 872544)),
        ),
    ]
