# Generated by Django 3.1.4 on 2025-04-05 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_auto_20250405_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricetype',
            name='price_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 12, 43, 24, 277237)),
        ),
    ]
