# Generated by Django 3.1.4 on 2025-04-05 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_auto_20250405_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='nds_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 16, 27, 3, 19989)),
        ),
    ]
