# Generated by Django 3.1.4 on 2025-04-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_auto_20250406_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 13, 58, 59, 794306)),
        ),
    ]
