# Generated by Django 3.1.4 on 2025-04-06 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_auto_20250406_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_kassa_tarixi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_nds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 14, 31, 34, 362877)),
        ),
    ]
