# Generated by Django 3.1.4 on 2025-04-07 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_auto_20250406_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 10, 41, 6, 771333)),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='product_filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
