# Generated by Django 3.1.4 on 2025-04-08 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_auto_20250407_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 13, 52, 10, 173215)),
        ),
    ]
