# Generated by Django 3.1.4 on 2025-04-09 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0231_auto_20250408_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 17, 23, 46, 777489)),
        ),
        migrations.CreateModel(
            name='RejaTushum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('plan_total', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
            ],
        ),
    ]
