# Generated by Django 3.1.4 on 2025-04-09 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_auto_20250409_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejatushum',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 17, 30, 28, 271508)),
        ),
    ]
