# Generated by Django 3.1.4 on 2025-04-09 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0233_auto_20250409_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejatushum',
            name='from_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 18, 38, 57, 299506)),
        ),
    ]
