# Generated by Django 3.1.4 on 2025-04-09 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0234_auto_20250409_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 19, 34, 34, 154561)),
        ),
        migrations.CreateModel(
            name='RejaChiqim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('plan_total', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('from_shop', models.BooleanField(default=False)),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop')),
            ],
        ),
    ]
