# Generated by Django 3.1.4 on 2025-04-09 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_auto_20250409_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 19, 35, 6, 996978)),
        ),
    ]
