# Generated by Django 3.1.4 on 2025-04-18 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_auto_20250409_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 17, 46, 34, 862060)),
        ),
    ]
