# Generated by Django 3.1.4 on 2025-04-19 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_auto_20250418_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverpaymentsall',
            name='recieve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recieve'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 10, 9, 3, 947450)),
        ),
    ]
