# Generated by Django 3.1.4 on 2025-04-19 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_auto_20250419_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 10, 9, 15, 318094)),
        ),
    ]
