# Generated by Django 3.1.4 on 2025-04-19 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0241_auto_20250419_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 15, 5, 38, 79432)),
        ),
        migrations.AlterField(
            model_name='returnproducttodeliveritem',
            name='returnproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnproducttodeliver', to='api.returnproducttodeliver'),
        ),
    ]
