# Generated by Django 3.1.4 on 2025-04-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0242_auto_20250419_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducttodeliver',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 16, 9, 28, 961807)),
        ),
    ]
