# Generated by Django 3.1.4 on 2025-04-21 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_auto_20250419_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtdeliver',
            name='recieve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recieve'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 11, 49, 17, 61013)),
        ),
    ]
