# Generated by Django 3.1.4 on 2025-04-21 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_auto_20250421_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 14, 13, 32, 216889)),
        ),
    ]
