# Generated by Django 3.1.4 on 2025-04-21 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_auto_20250421_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqimturi',
            name='for_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 15, 2, 14, 821947)),
        ),
    ]
