# Generated by Django 3.1.4 on 2025-05-05 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_auto_20250421_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomeUserTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tartib_raqam', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 14, 43, 11, 513582)),
        ),
        migrations.CreateModel(
            name='ExternalIncomeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('tartib_raqam', models.PositiveIntegerField(unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.externalincomeusertypes')),
                ('valyuta', models.ManyToManyField(blank=True, to='api.Valyuta')),
            ],
        ),
    ]
