# Generated by Django 3.1.4 on 2025-05-05 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_auto_20250505_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='external_income_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.externalincomeuser'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 15, 54, 15, 352708)),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
    ]
