# Generated by Django 3.1.4 on 2025-05-05 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_auto_20250505_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 16, 24, 25, 910595)),
        ),
        migrations.CreateModel(
            name='ExternalIncomeUserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('som', models.IntegerField(default=0)),
                ('dollar', models.IntegerField(default=0)),
                ('plastik', models.IntegerField(default=0)),
                ('hisob_raqam', models.IntegerField(default=0)),
                ('external_income_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.externalincomeuser')),
            ],
        ),
    ]
