# Generated by Django 3.1.4 on 2025-05-05 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0250_auto_20250505_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalincomeuserpayment',
            name='type_pay',
            field=models.IntegerField(choices=[(1, 'Pay'), (2, 'Give')], default=1),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 16, 51, 52, 640464)),
        ),
    ]
