# Generated by Django 3.1.4 on 2025-05-05 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0251_auto_20250505_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalincomeuserpayment',
            name='comment',
            field=models.TextField(blank=True, default='Izoh yo`q', null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 17, 14, 23, 398006)),
        ),
    ]
