# Generated by Django 3.1.4 on 2025-05-06 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0252_auto_20250505_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kassa',
            name='valyuta',
        ),
        migrations.AddField(
            model_name='kassa',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
        migrations.AddField(
            model_name='kassa',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 13, 55, 0, 527339)),
        ),
        migrations.CreateModel(
            name='KassaBiriktirsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_summa', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kassa')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
