# Generated by Django 3.1.4 on 2025-05-06 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0253_auto_20250506_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 13, 59, 41, 799996)),
        ),
    ]
