# Generated by Django 3.1.4 on 2025-05-06 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0255_auto_20250506_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 14, 22, 48, 323356)),
        ),
        migrations.AlterField(
            model_name='kassamerge',
            name='start_summa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kassamerge',
            name='summa',
            field=models.IntegerField(default=0),
        ),
    ]
