# Generated by Django 3.1.4 on 2025-05-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_auto_20250506_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 15, 5, 45, 804865)),
        ),
    ]
