# Generated by Django 3.1.4 on 2025-05-07 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0260_auto_20250507_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 17, 1, 31, 596212)),
        ),
    ]
