# Generated by Django 3.1.4 on 2025-05-07 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0261_auto_20250507_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebt',
            name='start_summa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 17, 51, 51, 214141)),
        ),
    ]
