# Generated by Django 3.1.4 on 2025-05-08 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_auto_20250507_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='summa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='type_pay',
            field=models.IntegerField(choices=[(1, 'Pay'), (2, 'Give')], default=1),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 9, 18, 59, 395340)),
        ),
    ]
