# Generated by Django 3.1.4 on 2025-05-08 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_auto_20250508_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 13, 26, 47, 818700)),
        ),
    ]
