# Generated by Django 3.1.4 on 2025-05-08 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_auto_20250508_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassamerge'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 17, 37, 6, 236376)),
        ),
    ]
