# Generated by Django 3.1.4 on 2025-05-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0264_auto_20250508_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='debt_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='debt_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='debt_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='debt_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 15, 23, 37, 749330)),
        ),
    ]
