# Generated by Django 3.1.4 on 2025-05-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_auto_20250508_1737'),
        ('api', '0265_auto_20250508_1523'),
    ]

    operations = [
    ]
