# Generated by Django 3.1.4 on 2025-05-10 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_auto_20250508_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 7, 30, 30, 262711)),
        ),
    ]
