# Generated by Django 3.1.4 on 2025-05-10 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_auto_20250510_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalincomeuserpayment',
            old_name='dollar',
            new_name='summa',
        ),
        migrations.RemoveField(
            model_name='externalincomeuserpayment',
            name='hisob_raqam',
        ),
        migrations.RemoveField(
            model_name='externalincomeuserpayment',
            name='plastik',
        ),
        migrations.RemoveField(
            model_name='externalincomeuserpayment',
            name='som',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 14, 34, 29, 688753)),
        ),
        migrations.RemoveField(
            model_name='externalincomeuser',
            name='valyuta',
        ),
        migrations.AddField(
            model_name='externalincomeuser',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.valyuta'),
        ),
    ]
