# Generated by Django 3.1.4 on 2025-05-08 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0266_merge_20250508_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='kassa_after',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 18, 2, 20, 483574)),
        ),
    ]
