# Generated by Django 3.1.4 on 2025-05-08 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0267_auto_20250508_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassamerge'),
        ),
        migrations.AddField(
            model_name='kirim',
            name='summa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kirim',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 18, 4, 32, 178701)),
        ),
    ]
