# Generated by Django 3.1.4 on 2025-05-10 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0268_auto_20250508_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirim',
            name='currency',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='kirim',
            name='kassa_new',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 11, 37, 57, 784166)),
        ),
    ]
