# Generated by Django 3.2 on 2025-05-12 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_auto_20250510_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiqimCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='chiqim',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassamerge'),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='kassa_new',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='summa',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='mobil_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mobiluser'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 12, 9, 52, 250145)),
        ),
        migrations.CreateModel(
            name='ChiqimSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chiqimcategory')),
            ],
        ),
        migrations.AddField(
            model_name='chiqim',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.chiqimsubcategory'),
        ),
    ]
