# Generated by Django 3.1.4 on 2025-05-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0269_auto_20250510_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 14, 49, 6, 145583)),
        ),
    ]
