# Generated by Django 3.2 on 2025-05-12 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_auto_20250512_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 12, 19, 11, 736325)),
        ),
    ]
