# Generated by Django 3.1.4 on 2025-05-10 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0270_auto_20250510_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalincomeuser',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 14, 51, 22, 455307)),
        ),
    ]
