# Generated by Django 3.1.4 on 2025-05-10 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0271_auto_20250510_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 10, 15, 0, 28, 175541)),
        ),
        migrations.CreateModel(
            name='ExternalIncomeUserDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(default=0)),
                ('start_summa', models.IntegerField(default=0)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.externalincomeuser')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
