# Generated by Django 3.2 on 2025-05-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0271_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='currency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 12, 20, 8, 203106)),
        ),
    ]
