# Generated by Django 3.1.4 on 2025-05-12 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_auto_20250510_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejatushum',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 9, 10, 44, 901433)),
        ),
    ]
