# Generated by Django 3.2 on 2025-05-12 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0272_auto_20250512_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valyuta',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='payhistory',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 16, 42, 47, 841199)),
        ),
    ]
