# Generated by Django 3.2 on 2025-05-13 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0273_auto_20250512_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='payhistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payhistory'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 12, 4, 32, 194146)),
        ),
    ]
