# Generated by Django 3.1.4 on 2025-05-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_auto_20250512_1208'),
        ('api', '0272_auto_20250512_1220'),
    ]

    operations = [
    ]
