# Generated by Django 3.2 on 2025-05-13 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0274_auto_20250513_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDebt',
            new_name='Wallet',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 12, 42, 38, 382548)),
        ),
    ]
