# Generated by Django 3.1.4 on 2025-05-12 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0275_merge_20250512_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valyuta',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 14, 45, 0, 929340)),
        ),
    ]
