# Generated by Django 3.1.4 on 2025-05-13 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_auto_20250512_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainToolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 12, 32, 39, 431634)),
        ),
        migrations.CreateModel(
            name='MainTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('summa', models.FloatField(default=0)),
                ('wear', models.FloatField(default=0)),
                ('today_stayed', models.FloatField(default=0)),
                ('use_month', models.IntegerField(default=0)),
                ('wear_month_summa', models.IntegerField(default=0)),
                ('tool_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maintooltype')),
            ],
        ),
    ]
