# Generated by Django 3.2 on 2025-05-13 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0276_auto_20250513_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='debt_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recieve',
            name='debt_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 15, 45, 33, 664102)),
        ),
    ]
