# Generated by Django 3.1.4 on 2025-05-13 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_auto_20250513_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintool',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 12, 34, 57, 337770)),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
