# Generated by Django 3.1.4 on 2025-05-13 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0278_auto_20250513_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintool',
            options={'verbose_name_plural': 'Asossiy Vosita'},
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 12, 44, 34, 452352)),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='today_stayed',
            field=models.FloatField(default=0, verbose_name='Bugungi qoldiq'),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='use_month',
            field=models.IntegerField(default=0, verbose_name='Foydalanish oyi'),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='wear',
            field=models.FloatField(default=0, verbose_name='Toplangan eskirish'),
        ),
        migrations.AlterField(
            model_name='maintool',
            name='wear_month_summa',
            field=models.IntegerField(default=0, verbose_name='Oylik eskirish summasi'),
        ),
    ]
