# Generated by Django 3.1.4 on 2025-05-13 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0279_auto_20250513_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 2, 20, 931638)),
        ),
    ]
