# Generated by Django 3.1.4 on 2025-05-13 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0280_auto_20250513_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintool',
            old_name='number',
            new_name='inventory_number',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 3, 7, 972568)),
        ),
    ]
