# Generated by Django 3.1.4 on 2025-05-13 14:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0281_auto_20250513_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintool',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 19, 9, 387835)),
        ),
    ]
