# Generated by Django 3.1.4 on 2025-05-13 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0282_auto_20250513_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 19, 22, 614774)),
        ),
    ]
