# Generated by Django 3.1.4 on 2025-05-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0277_auto_20250513_1545'),
        ('api', '0283_auto_20250513_1419'),
    ]

    operations = [
    ]
