# Generated by Django 3.1.4 on 2025-05-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0284_merge_20250513_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 18, 28, 17, 734680)),
        ),
        migrations.DeleteModel(
            name='ExternalIncomeUserDebt',
        ),
    ]
