# Generated by Django 5.2.1 on 2025-05-14 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0285_auto_20250513_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 13, 38, 42, 51773)),
        ),
    ]
