# Generated by Django 3.1.4 on 2025-05-15 03:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0285_auto_20250513_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 3, 16, 25, 405305)),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.externalincomeuser')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
