# Generated by Django 5.2.1 on 2025-05-15 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0286_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 10, 27, 9, 85460)),
        ),
    ]
