# Generated by Django 3.1.4 on 2025-05-15 03:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0286_auto_20250515_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 3, 18, 39, 235307)),
        ),
    ]
