# Generated by Django 3.1.4 on 2025-05-15 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_auto_20250515_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='debt_new',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bonus',
            name='debt_old',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 10, 31, 59, 405787)),
        ),
    ]
