# Generated by Django 5.2.1 on 2025-05-16 16:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 15, 7, 980652)),
        ),
    ]
