# Generated by Django 4.2.21 on 2025-05-18 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 0, 24, 30, 357783)),
        ),
    ]
