# Generated by Django 3.1.4 on 2025-05-15 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0288_auto_20250515_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 10, 33, 1, 360916)),
        ),
    ]
