# Generated by Django 3.1.4 on 2025-05-15 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0289_auto_20250515_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='customer',
            new_name='debtor',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 10, 39, 29, 663775)),
        ),
    ]
