# Generated by Django 5.2.1 on 2025-05-16 16:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0289_rejachiqim_kassa_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 18, 28, 449790)),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassanew'),
        ),
    ]
