# Generated by Django 3.1.4 on 2025-05-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0290_auto_20250515_1039'),
        ('api', '0287_alter_debtor_start_date'),
    ]

    operations = [
    ]
