# Generated by Django 4.2.21 on 2025-05-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0287_alter_debtor_start_date'),
        ('api', '0290_auto_20250515_1039'),
    ]

    operations = [
    ]
