# Generated by Django 5.2.1 on 2025-05-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0290_alter_debtor_start_date_alter_rejachiqim_kassa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 29, 27, 164676)),
        ),
    ]
