# Generated by Django 4.2.21 on 2025-05-16 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0291_merge_20250515_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summa_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 10, 52, 24, 156077)),
        ),
    ]
