# Generated by Django 5.2.1 on 2025-05-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0291_rejachiqim_is_active_rejachiqim_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 29, 56, 545702)),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
