# Generated by Django 4.2.21 on 2025-05-18 01:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0292_cart_summa_total_alter_debtor_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricetype',
            name='price_dollar',
        ),
        migrations.AddField(
            model_name='productpricetype',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_types', to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 1, 19, 11, 443772)),
        ),
    ]
