# Generated by Django 5.2.1 on 2025-05-16 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0292_alter_debtor_start_date_alter_rejachiqim_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 34, 15, 821166)),
        ),
    ]
