# Generated by Django 5.2.1 on 2025-05-16 16:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0293_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejatushum',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver'),
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='external_income_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.externalincomeuser'),
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassanew'),
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 46, 21, 428581)),
        ),
    ]
