# Generated by Django 4.2.21 on 2025-05-19 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0294_alter_debtor_start_date_productbringprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 10, 5, 20, 902483)),
        ),
        migrations.DeleteModel(
            name='ProductBringPrice',
        ),
    ]
