# Generated by Django 5.2.1 on 2025-05-16 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0294_rejatushum_deliver_rejatushum_external_income_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejachiqim',
            name='where',
        ),
        migrations.AddField(
            model_name='rejatushum',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 56, 15, 412693)),
        ),
    ]
