# Generated by Django 5.2.1 on 2025-05-16 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0295_remove_rejachiqim_where_rejatushum_where_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 17, 57, 52, 915111)),
        ),
    ]
