# Generated by Django 5.2.1 on 2025-05-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0290_auto_20250515_1039'),
        ('api', '0296_rejachiqim_where_alter_debtor_start_date'),
    ]

    operations = [
    ]
