# Generated by Django 4.2.21 on 2025-05-19 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0296_alter_debtor_start_date_productbringprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbringprice',
            name='recieveitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recieveitem'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 11, 9, 14, 131804)),
        ),
    ]
