# Generated by Django 3.1.4 on 2025-05-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0296_rejachiqim_where_alter_debtor_start_date'),
        ('api', '0291_merge_20250515_1623'),
    ]

    operations = [
    ]
