# Generated by Django 5.2.1 on 2025-05-17 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_merge_20250517_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassadaily',
            name='summa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 14, 54, 16, 339874)),
        ),
    ]
