# Generated by Django 4.2.21 on 2025-05-19 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_productbringprice_recieveitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieveExpanseTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 13, 48, 23, 377191)),
        ),
        migrations.CreateModel(
            name='RecieveExpanses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('externaluser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.externalincomeuser')),
                ('recieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanses', to='api.recieve')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.recieveexpansetypes')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
