# Generated by Django 3.1.4 on 2025-05-16 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0297_merge_20250516_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
