# Generated by Django 4.2.21 on 2025-05-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0298_recieveexpansetypes_alter_debtor_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='kurs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 14, 38, 54, 200197)),
        ),
    ]
