# Generated by Django 5.2.1 on 2025-05-17 14:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0298_kassadaily_summa_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassadaily',
            name='kassa_merge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassamerge'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 14, 55, 29, 123988)),
        ),
    ]
