# Generated by Django 4.2.21 on 2025-05-19 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0299_recieve_kurs_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='is_som',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 19, 14, 44, 56, 670317)),
        ),
    ]
