# Generated by Django 5.2.1 on 2025-05-17 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0299_kassadaily_kassa_merge_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 17, 14, 55, 37, 307084)),
        ),
    ]
