# Generated by Django 3.1.4 on 2025-05-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0298_auto_20250516_1855'),
        ('api', '0300_valyuta_is_som_alter_debtor_start_date'),
    ]

    operations = [
    ]
