# Generated by Django 5.2.1 on 2025-05-21 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0301_rejachiqim_is_majburiyat_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 11, 53, 31, 390225)),
        ),
    ]
