# Generated by Django 5.2.1 on 2025-05-21 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0302_rejachiqim_deadline_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 21, 5, 740347)),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 12, 21, 5, 864984)),
        ),
    ]
