# Generated by Django 5.2.1 on 2025-05-21 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0303_alter_debtor_start_date_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 12, 42, 51, 706849)),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 12, 42, 51, 827981)),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='is_majburiyat',
            field=models.BooleanField(default=False),
        ),
    ]
