# Generated by Django 5.2.1 on 2025-05-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0301_merge_20250519_1606'),
        ('api', '0304_alter_debtor_start_date_alter_rejachiqim_date_and_more'),
    ]

    operations = [
    ]
