# Generated by Django 5.2.1 on 2025-05-21 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0305_merge_20250521_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 13, 52, 40, 688284)),
        ),
    ]
