# Generated by Django 5.2.1 on 2025-05-21 15:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0306_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='reja_chiqim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rejachiqim'),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 15, 38, 2, 896671)),
        ),
    ]
