# Generated by Django 3.1.4 on 2025-05-22 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_chiqim_reja_chiqim_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 22, 15, 19, 41, 144314)),
        ),
    ]
