# Generated by Django 4.2.21 on 2025-05-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_chiqim_reja_chiqim_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 24, 12, 0, 39, 920156)),
        ),
    ]
