# Generated by Django 5.2.1 on 2025-05-27 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0307_chiqim_reja_chiqim_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 27, 10, 56, 51, 986935)),
        ),
    ]
