# Generated by Django 3.1.4 on 2025-05-23 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0308_auto_20250522_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 23, 10, 18, 38, 326739)),
        ),
    ]
