# Generated by Django 3.1.4 on 2025-05-24 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0309_auto_20250523_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 24, 15, 48, 30, 612105)),
        ),
    ]
