# Generated by Django 3.1.4 on 2025-05-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0308_debtor_tg_id_alter_rejachiqim_date'),
        ('api', '0310_auto_20250524_1548'),
    ]

    operations = [
    ]
