# Generated by Django 3.1.4 on 2025-05-27 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0311_merge_20250527_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 27, 11, 10, 42, 430502)),
        ),
    ]
