# Generated by Django 4.2.21 on 2025-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0308_alter_rejachiqim_date'),
        ('api', '0312_auto_20250527_1110'),
    ]

    operations = [
    ]
