# Generated by Django 5.2.1 on 2025-05-28 09:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0312_auto_20250527_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 9, 42, 30, 604798)),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'completed')], default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('summa', models.IntegerField(default=0)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filial')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('arrival_price', models.IntegerField(default=0, verbose_name='Kelish narx')),
                ('selling_price', models.IntegerField(default=0, verbose_name='Sotish narx')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.revision')),
            ],
        ),
    ]
