# Generated by Django 4.2.21 on 2025-05-28 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0313_merge_20250528_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoffitem',
            name='prices',
            field=models.ManyToManyField(blank=True, to='api.productbringprice'),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 11, 45, 42, 725372)),
        ),
    ]
