# Generated by Django 5.2.1 on 2025-05-28 11:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0313_alter_rejachiqim_date_revision_revisionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricetype'),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 11, 49, 39, 522383)),
        ),
    ]
