# Generated by Django 5.2.1 on 2025-05-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0314_revision_price_type_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionitems',
            name='old_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 29, 12, 6, 12, 642589)),
        ),
    ]
