# Generated by Django 4.2.21 on 2025-05-28 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0314_writeoffitem_prices_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducttodeliveritem',
            name='summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 19, 45, 10, 393618)),
        ),
    ]
