# Generated by Django 3.1.4 on 2025-05-28 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0314_revision_price_type_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 15, 53, 19, 629797)),
        ),
    ]
