# Generated by Django 3.1.4 on 2025-05-28 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0315_auto_20250528_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 28, 15, 53, 38, 930003)),
        ),
    ]
