# Generated by Django 5.2.1 on 2025-05-30 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0317_alter_productfilial_quantity_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='start_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 9, 21, 14, 506738)),
        ),
    ]
