# Generated by Django 5.2.1 on 2025-05-30 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0318_alter_productfilial_start_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 9, 42, 14, 706810)),
        ),
        migrations.AlterField(
            model_name='revisionitems',
            name='arrival_price',
            field=models.FloatField(default=0, verbose_name='Kelish narx'),
        ),
        migrations.AlterField(
            model_name='revisionitems',
            name='old_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revisionitems',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revisionitems',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Sotish narx'),
        ),
    ]
