# Generated by Django 5.2.1 on 2025-05-30 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0320_alter_cart_price_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveitem',
            name='old_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recieveitem',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 10, 28, 32, 940306)),
        ),
    ]
