# Generated by Django 5.2.1 on 2025-05-30 10:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0321_alter_recieveitem_old_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeoff',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 30, 10, 42, 47, 718780)),
        ),
    ]
