# Generated by Django 3.1.4 on 2025-05-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0322_writeoff_valyuta_alter_rejachiqim_date'),
        ('api', '0316_auto_20250528_1553'),
    ]

    operations = [
    ]
