# Generated by Django 4.2.21 on 2025-05-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0315_returnproducttodeliveritem_summa_and_more'),
        ('api', '0322_writeoff_valyuta_alter_rejachiqim_date'),
    ]

    operations = [
    ]
