# Generated by Django 5.2.1 on 2025-05-31 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0323_userprofile_is_bugungi_amaliyotlar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='qaysi_oy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 12, 5, 3, 376016)),
        ),
    ]
