# Generated by Django 3.1.4 on 2025-06-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0323_merge_20250531_0306'),
        ('api', '0323_merge_20250530_1108'),
    ]

    operations = [
    ]
