# Generated by Django 5.2.1 on 2025-05-31 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0324_rejachiqim_qaysi_oy_alter_rejachiqim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='qaysi_oy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
