# Generated by Django 5.2.1 on 2025-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0325_alter_rejachiqim_date_alter_rejachiqim_qaysi_oy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='qaysi_oy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
