# Generated by Django 5.2.1 on 2025-06-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0326_alter_rejachiqim_qaysi_oy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejachiqim',
            old_name='qaysi_oy',
            new_name='qaysi',
        ),
    ]
