# Generated by Django 5.2.1 on 2025-06-02 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0327_rename_qaysi_oy_rejachiqim_qaysi'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiqim',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AddField(
            model_name='chiqim',
            name='qaysi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
