# Generated by Django 5.2.1 on 2025-06-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0328_chiqim_money_circulation_chiqim_qaysi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='valyuta',
        ),
    ]
