# Generated by Django 5.2.1 on 2025-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0329_remove_revision_price_type_remove_revision_valyuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionitems',
            name='arrival_price',
        ),
        migrations.RemoveField(
            model_name='revisionitems',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='revisionitems',
            name='dollar_arrival_price',
            field=models.FloatField(default=0, verbose_name='Dollar Kelish narx'),
        ),
        migrations.AddField(
            model_name='revisionitems',
            name='som_arrival_price',
            field=models.FloatField(default=0, verbose_name='Som Kelish narx'),
        ),
    ]
