# Generated by Django 5.2.1 on 2025-06-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0324_merge_20250602_1724'),
        ('api', '0330_remove_revisionitems_arrival_price_and_more'),
    ]

    operations = [
    ]
