# Generated by Django 5.2.1 on 2025-06-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0332_remove_returnproducttodeliver_valyuta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
    ]
