# Generated by Django 5.2.1 on 2025-06-09 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0333_alter_morder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mcart',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mcart',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiluser'),
        ),
    ]
