# Generated by Django 5.2.1 on 2025-06-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0334_alter_mcart_price_alter_mcart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pricetype'),
        ),
    ]
