# Generated by Django 5.2.1 on 2025-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0335_debtor_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='ready',
            field=models.IntegerField(choices=[(1, 'xom ashyo'), (2, 'yarim tayyor'), (3, 'tayyor')], default='1'),
        ),
    ]
