# Generated by Django 4.2.21 on 2025-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0335_debtor_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='naqd',
            field=models.BooleanField(default=False),
        ),
    ]
