# Generated by Django 3.1.4 on 2025-06-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0335_debtor_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverpaymentsall', to='api.deliver'),
        ),
    ]
