# Generated by Django 3.1.4 on 2025-06-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0336_auto_20250614_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpayments',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverpayments', to='api.deliver'),
        ),
    ]
