# Generated by Django 5.2.1 on 2025-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0336_productfilial_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='status',
            field=models.IntegerField(choices=[(1, 'new'), (2, 'done'), (3, 'rejected')], default=1),
        ),
    ]
