# Generated by Django 4.2.21 on 2025-06-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0336_debtor_naqd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='phone1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
