# Generated by Django 5.2.1 on 2025-06-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0337_alter_debtor_phone1'),
        ('api', '0337_morder_status'),
    ]

    operations = [
    ]
