# Generated by Django 4.2.21 on 2025-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0337_alter_debtor_phone1'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='pack',
            field=models.FloatField(default=0),
        ),
    ]
