# Generated by Django 3.1.4 on 2025-06-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0337_alter_debtor_phone1'),
        ('api', '0337_auto_20250614_1644'),
    ]

    operations = [
    ]
