# Generated by Django 3.1.4 on 2025-06-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0338_merge_20250614_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverpayments',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverpayments', to='api.deliver'),
        ),
        migrations.AlterField(
            model_name='deliverpaymentsall',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliverpaymentsall', to='api.deliver'),
        ),
        migrations.AlterField(
            model_name='rejachiqim',
            name='qaysi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
