# Generated by Django 3.1.4 on 2025-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0339_auto_20250614_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintool',
            options={'verbose_name_plural': 'Asosiy Vositalar'},
        ),
    ]
