# Generated by Django 3.1.4 on 2025-06-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0340_auto_20250616_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejachiqim',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='from_shop',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='is_majburiyat',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='kassa',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='money_circulation',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='plan_total',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='total',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='valyuta',
        ),
        migrations.RemoveField(
            model_name='rejachiqim',
            name='where',
        ),
    ]
