# Generated by Django 3.1.4 on 2025-06-16 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0341_auto_20250616_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.debtor'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='from_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='is_majburiyat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kassanew'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='kurs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='money_circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.moneycirculation'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='plan_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='valyuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.valyuta'),
        ),
        migrations.AddField(
            model_name='rejachiqim',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
