# Generated by Django 3.1.4 on 2025-06-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0342_auto_20250616_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejachiqim',
            name='qaysi',
        ),
    ]
