# Generated by Django 3.1.4 on 2025-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0343_remove_rejachiqim_qaysi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='qaysi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
