# Generated by Django 3.1.4 on 2025-06-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0344_rejachiqim_qaysi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
