# Generated by Django 3.1.4 on 2025-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0345_auto_20250616_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='qarz_dol',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filial',
            name='qarz_som',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filial',
            name='savdo_puli_dol',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filial',
            name='savdo_puli_som',
            field=models.BigIntegerField(default=0),
        ),
    ]
