# Generated by Django 3.1.4 on 2025-06-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0346_auto_20250616_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbringprice',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
    ]
