# Generated by Django 3.1.4 on 2025-06-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0338_merge_0337_alter_debtor_phone1_0337_morder_status'),
        ('api', '0347_productbringprice_sell_price'),
    ]

    operations = [
    ]
