# Generated by Django 4.2.21 on 2025-06-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0338_merge_0337_alter_debtor_phone1_0337_morder_status'),
        ('api', '0338_productfilial_pack'),
        ('api', '0347_productbringprice_sell_price'),
    ]

    operations = [
    ]
