# Generated by Django 4.2.21 on 2025-06-17 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0348_merge_20250617_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbringprice',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='productfilial',
            name='pack',
        ),
        migrations.CreateModel(
            name='ProductSellPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
