# Generated by Django 4.2.21 on 2025-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0349_remove_productbringprice_sell_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_pack',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductSellPrice',
        ),
    ]
