# Generated by Django 4.2.21 on 2025-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0350_cart_total_pack_delete_productsellprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='pack',
            field=models.FloatField(default=0),
        ),
    ]
