# Generated by Django 4.2.21 on 2025-06-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0351_productfilial_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='Sahifa URL manzili')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Video nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Video qo'llanma",
                'verbose_name_plural': "Video qo'llanmalar",
                'unique_together': {('url',)},
            },
        ),
    ]
