# Generated by Django 4.2.21 on 2025-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0352_videotutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='season',
            field=models.CharField(blank=True, choices=[('bahor', 'Bahor'), ('yoz', 'Yoz'), ('kuz', 'Kuz'), ('qish', 'Qish')], max_length=20, null=True),
        ),
    ]
