# Generated by Django 3.1.4 on 2025-06-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0352_videotutorial'),
        ('api', '0348_merge_20250618_1541'),
    ]

    operations = [
    ]
