# Generated by Django 4.2.21 on 2025-06-26 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0353_productfilial_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieve',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
