# Generated by Django 3.1.4 on 2025-06-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0353_productfilial_season'),
        ('api', '0353_merge_20250618_1546'),
    ]

    operations = [
    ]
