# Generated by Django 5.2.1 on 2025-06-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0354_productbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
