# Generated by Django 4.2.21 on 2025-06-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0354_recieve_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
