# Generated by Django 5.2.1 on 2025-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0355_alter_productbarcode_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
