# Generated by Django 4.2.21 on 2025-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0355_alter_recieve_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='main_warehouse',
            field=models.BooleanField(default=True),
        ),
    ]
