# Generated by Django 4.2.21 on 2025-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0356_filial_main_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='main_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
