# Generated by Django 5.2.1 on 2025-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0357_recieve_comment_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
