# Generated by Django 5.2.1 on 2025-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0358_valyuta_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.IntegerField(choices=[(1, 'Yaratildi'), (2, 'Tasdiqlandi'), (3, 'Qaytarildi')], default=1),
        ),
    ]
