# Generated by Django 3.2 on 2025-06-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0357_alter_filial_main_warehouse'),
        ('api', '0359_shop_status'),
    ]

    operations = [
    ]
