# Generated by Django 5.2.1 on 2025-06-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0359_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='shelf_code',
            field=models.IntegerField(default=0),
        ),
    ]
