# Generated by Django 3.1.4 on 2025-06-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0359_shop_status'),
        ('api', '0354_merge_20250621_1131'),
    ]

    operations = [
    ]
