# Generated by Django 4.2.21 on 2025-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0360_merge_20250627_1649'),
        ('api', '0360_productfilial_shelf_code'),
    ]

    operations = [
    ]
