# Generated by Django 3.1.4 on 2025-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0360_merge_20250628_0345'),
        ('api', '0360_productfilial_shelf_code'),
    ]

    operations = [
    ]
