# Generated by Django 3.1.4 on 2025-06-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0361_merge_20250628_0845'),
        ('api', '0360_merge_20250627_1649'),
    ]

    operations = [
    ]
