# Generated by Django 4.2.21 on 2025-07-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0361_merge_20250630_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groups'),
        ),
        migrations.AlterField(
            model_name='productfilial',
            name='season',
            field=models.CharField(blank=True, choices=[('yoz', 'Yoz'), ('qish', 'Qish')], max_length=20, null=True),
        ),
    ]
