# Generated by Django 3.1.4 on 2025-07-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0362_merge_20250630_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morder',
            name='products',
        ),
        migrations.AlterField(
            model_name='productfilial',
            name='season',
            field=models.CharField(blank=True, choices=[('yoz', 'Yoz'), ('qish', 'Qish')], max_length=20, null=True),
        ),
    ]
