# Generated by Django 3.1.4 on 2025-07-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0363_auto_20250701_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcart',
            name='m_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.morder'),
        ),
    ]
