# Generated by Django 3.1.4 on 2025-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0364_mcart_m_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
