# Generated by Django 3.1.4 on 2025-07-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0365_morder_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
