# Generated by Django 3.1.4 on 2025-07-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0366_auto_20250701_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcart',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
