# Generated by Django 5.2.1 on 2025-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0367_mcart_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='skidka_total',
            field=models.FloatField(default=0),
        ),
    ]
