# Generated by Django 5.2.1 on 2025-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0368_alter_cart_skidka_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='is_debt',
            field=models.BooleanField(default=False),
        ),
    ]
