# Generated by Django 5.2.1 on 2025-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0369_payhistory_is_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
