# Generated by Django 5.2.1 on 2025-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0370_payhistory_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejachiqim',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
