# Generated by Django 5.2.1 on 2025-07-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0371_alter_rejachiqim_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
