# Generated by Django 3.1.4 on 2025-07-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0371_alter_rejachiqim_payment_date'),
        ('api', '0371_auto_20250703_1629'),
    ]

    operations = [
    ]
