# Generated by Django 5.2.1 on 2025-07-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0372_alter_recieve_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
