# Generated by Django 3.1.4 on 2025-07-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0372_merge_20250705_1542'),
        ('api', '0372_alter_recieve_name'),
    ]

    operations = [
    ]
