# Generated by Django 3.1.4 on 2025-07-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0373_merge_20250705_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcode',
            name='barcode',
            field=models.CharField(max_length=255),
        ),
    ]
