# Generated by Django 5.2.1 on 2025-07-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0373_groups_is_active_groups_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
