# Generated by Django 4.2.21 on 2025-07-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0362_alter_productfilial_group_alter_productfilial_season'),
        ('api', '0373_groups_is_active_groups_number'),
        ('api', '0374_auto_20250707_1821'),
    ]

    operations = [
    ]
