# Generated by Django 5.2.1 on 2025-07-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0374_alter_shop_filial'),
        ('api', '0374_auto_20250707_1821'),
    ]

    operations = [
    ]
