# Generated by Django 5.2.1 on 2025-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0375_merge_0374_alter_shop_filial_0374_auto_20250707_1821'),
        ('api', '0375_merge_20250708_0448'),
    ]

    operations = [
    ]
