# Generated by Django 3.1.4 on 2025-07-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0375_merge_20250708_0448'),
        ('api', '0375_merge_0374_alter_shop_filial_0374_auto_20250707_1821'),
    ]

    operations = [
    ]
