# Generated by Django 5.2.1 on 2025-07-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0376_merge_20250708_1425'),
        ('api', '0378_auto_20250708_1732'),
    ]

    operations = [
    ]
