# Generated by Django 5.2.1 on 2025-07-11 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0379_merge_20250709_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kassanew')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valyuta')),
            ],
        ),
    ]
