# Generated by Django 5.2.1 on 2025-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0380_closecash'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
