# Generated by Django 5.2.1 on 2025-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0381_closecash_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='chegirma',
            field=models.FloatField(default=0),
        ),
    ]
