# Generated by Django 5.2.1 on 2025-07-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0382_shop_chegirma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debt_new', models.FloatField(default=0)),
                ('debt_old', models.FloatField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.debtor')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.filial')),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.valyuta')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnCustomerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productfilial')),
                ('return_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.returncustomer')),
            ],
        ),
    ]
