# Generated by Django 5.2.1 on 2025-07-16 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0383_returncustomer_returncustomeritems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returncustomer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
