# Generated by Django 5.2.1 on 2025-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0384_alter_returncustomer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_grop/'),
        ),
    ]
