# Generated by Django 3.1.4 on 2025-07-21 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0384_alter_returncustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
