# Generated by Django 5.2.1 on 2025-07-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0385_groups_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
