# Generated by Django 3.1.4 on 2025-07-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0385_groups_image'),
        ('api', '0385_auto_20250721_1603'),
    ]

    operations = [
    ]
