# Generated by Django 3.1.4 on 2025-07-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0386_alter_debtor_tg_id'),
        ('api', '0385_auto_20250721_1603'),
    ]

    operations = [
    ]
