# Generated by Django 3.1.4 on 2025-07-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0386_alter_debtor_tg_id'),
        ('api', '0386_merge_20250723_1720'),
    ]

    operations = [
    ]
