# Generated by Django 4.2.21 on 2025-07-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0288_alter_debtor_start_date'),
        ('api', '0387_merge_20250725_1911'),
    ]

    operations = [
    ]
