# Generated by Django 3.1.4 on 2025-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0387_merge_20250724_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilial',
            name='ready',
            field=models.IntegerField(blank=True, choices=[(1, 'xom ashyo'), (2, 'yarim tayyor'), (3, 'tayyor')], null=True),
        ),
    ]
