# Generated by Django 4.2.21 on 2025-07-28 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0388_merge_20250728_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilial',
            name='deliver',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
