# Generated by Django 4.2.21 on 2025-07-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0389_remove_productfilial_deliver_alter_debtor_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ManyToManyField(blank=True, related_name='products1', to='api.deliver'),
        ),
    ]
