# Generated by Django 4.2.21 on 2025-07-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0390_productfilial_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfilial',
            name='deliver',
        ),
    ]
