# Generated by Django 4.2.21 on 2025-07-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0391_remove_productfilial_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product1', to='api.deliver'),
        ),
    ]
