# Generated by Django 3.1.4 on 2025-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0392_productfilial_deliver'),
        ('api', '0388_auto_20250727_1519'),
    ]

    operations = [
    ]
