# Generated by Django 3.1.4 on 2025-07-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0393_merge_20250728_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbarcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='api.productfilial'),
        ),
    ]
