# Generated by Django 3.1.4 on 2025-09-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0394_auto_20250728_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseCash',
        ),
    ]
