# Generated by Django 3.1.4 on 2025-09-08 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0395_delete_closecash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseCash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('kassa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kassamerge')),
            ],
        ),
    ]
