# Generated by Django 3.1.4 on 2025-09-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0396_closecash'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='closecash',
            name='kassa_new',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='closecash',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
