# Generated by Django 3.1.4 on 2025-09-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0397_auto_20250908_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='to_kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_kassa', to='api.kassanew'),
        ),
        migrations.AlterField(
            model_name='closecash',
            name='kassa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_kassa', to='api.kassamerge'),
        ),
    ]
