# Generated by Django 3.1.4 on 2025-09-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0398_auto_20250908_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closecash',
            name='to_kassa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_kassa', to='api.kassamerge'),
        ),
    ]
