# Generated by Django 3.1.4 on 2025-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0399_auto_20250908_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
