# Generated by Django 3.1.4 on 2025-09-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0400_productfilial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.filial'),
        ),
    ]
