# Generated by Django 3.1.4 on 2025-09-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0401_closecash_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='som_new',
            field=models.FloatField(default=0),
        ),
    ]
