# Generated by Django 3.1.4 on 2025-09-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0402_payhistory_som_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payhistory',
            old_name='som_new',
            new_name='kassa_new',
        ),
    ]
