# Generated by Django 3.1.4 on 2025-09-25 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0403_auto_20250925_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closecash',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
