# Generated by Django 3.1.4 on 2025-09-25 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0404_auto_20250925_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmenaClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closecashes', models.ManyToManyField(blank=True, to='api.CloseCash')),
            ],
        ),
    ]
