# Generated by Django 3.1.4 on 2025-09-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0405_smenaclose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmenaClose',
        ),
    ]
