# Generated by Django 3.1.4 on 2025-09-25 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0406_delete_smenaclose'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmenaClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_id', models.CharField(blank=True, max_length=200, null=True)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('closecashes', models.ManyToManyField(blank=True, to='api.CloseCash')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.filial')),
            ],
        ),
    ]
