# Generated by Django 3.1.4 on 2025-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0407_smenaclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='smenaclose',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
