# Generated by Django 3.1.4 on 2025-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0408_smenaclose_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='summa_confirmed',
            field=models.FloatField(default=0),
        ),
    ]
