# Generated by Django 3.1.4 on 2025-09-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0409_closecash_summa_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cart'),
        ),
    ]
