# Generated by Django 3.1.4 on 2025-09-26 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0410_returnproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='returnproduct',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
