# Generated by Django 3.1.4 on 2025-09-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0411_auto_20250926_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
