# Generated by Django 3.1.4 on 2025-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0412_returnproduct_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='Nechta xonagacha sonligi')),
                ('rounding_direction', models.IntegerField(choices=[(1, 'Tepaga yahlitlash (0.5 → 1)'), (2, 'Standart yahlitlash (0.5 → 1, 0.4 → 0)'), (3, 'Pastga yahlitlash (0.5 → 0)')], default=2, verbose_name="Yahlitlash yo'nalishi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yahlitlash sozlamasi',
                'verbose_name_plural': 'Yahlitlash sozlamalari',
            },
        ),
    ]
