# Generated by Django 3.1.4 on 2025-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0413_roundingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhistory',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
