# Generated by Django 3.1.4 on 2025-10-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0414_auto_20251003_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='api.cart'),
        ),
    ]
