# Generated by Django 3.1.4 on 2025-10-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0415_auto_20251003_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='chiqim_set',
            field=models.ManyToManyField(blank=True, to='api.Chiqim'),
        ),
    ]
