# Generated by Django 3.1.4 on 2025-10-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0416_returnproduct_chiqim_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='chiqim_set',
            field=models.ManyToManyField(blank=True, to='api.Chiqim'),
        ),
    ]
