# Generated by Django 3.1.4 on 2025-10-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0417_shop_chiqim_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='chiqim_set',
            new_name='chiqims',
        ),
    ]
