# Generated by Django 3.1.4 on 2025-11-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0421_auto_20251106_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='isclose_cash',
            new_name='is_close_cash',
        ),
    ]
