# Generated by Django 3.1.4 on 2025-11-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0422_auto_20251106_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_product_filail_zero',
            field=models.BooleanField(default=False),
        ),
    ]
