# Generated by Django 3.1.4 on 2025-11-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0423_userprofile_is_product_filail_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='closecash',
            name='rest_summa',
            field=models.FloatField(default=0),
        ),
    ]
