# Generated by Django 3.1.4 on 2025-11-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0424_closecash_rest_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='smenaclose',
            name='smenaopen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.smenaopen'),
        ),
    ]
