# Generated by Django 3.1.4 on 2025-11-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0425_smenaclose_smenaopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='is_som_or_dollar',
            field=models.BooleanField(default=False),
        ),
    ]
