# Generated by Django 3.1.4 on 2025-11-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0426_valyuta_is_som_or_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='return_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.returnproduct'),
        ),
    ]
