# Generated by Django 3.1.4 on 2025-11-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0427_payhistory_return_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='for_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payhistory'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_pays', to='api.shop'),
        ),
    ]
