# Generated by Django 3.1.4 on 2025-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0428_auto_20251117_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kassamerge',
            name='start_summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kassamerge',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
