# Generated by Django 3.1.4 on 2025-11-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0430_auto_20251120_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='main_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_children', to='api.payhistory'),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='for_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_children', to='api.payhistory'),
        ),
    ]
