# Generated by Django 3.1.4 on 2025-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0431_auto_20251124_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='from_refresh',
            field=models.BooleanField(default=False),
        ),
    ]
