# Generated by Django 3.1.4 on 2025-11-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0432_payhistory_from_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='from_refresh',
        ),
    ]
