# Generated by Django 3.1.4 on 2025-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0433_remove_payhistory_from_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
