# Generated by Django 3.1.4 on 2025-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0435_payhistory_for_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='start_summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='summa',
            field=models.FloatField(default=0),
        ),
    ]
