# Generated by Django 3.1.4 on 2025-11-28 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0436_auto_20251127_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashConvertHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cash_before', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('from_cash_after', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('to_cash_before', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('to_cash_after', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('summa2', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('currency', models.DecimalField(decimal_places=2, default=0, max_digits=155)),
                ('comment', models.CharField(default='Kassalar urtasida convert', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('converter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.userprofile')),
                ('from_cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_cash', to='api.kassamerge')),
                ('from_valuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_valuta', to='api.valyuta')),
                ('pay1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_convert_from_payment', to='api.payhistory')),
                ('pay2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_convert_to_payment', to='api.payhistory')),
                ('to_cash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_cash', to='api.kassamerge')),
                ('to_valuta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_valuta', to='api.valyuta')),
            ],
            options={
                'verbose_name_plural': 'Kassalar urtasida convert',
            },
        ),
    ]
