# Generated by Django 3.1.4 on 2025-11-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0437_cashconverthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashconverthistory',
            old_name='from_valuta',
            new_name='from_valyuta',
        ),
        migrations.RenameField(
            model_name='cashconverthistory',
            old_name='to_valuta',
            new_name='to_valyuta',
        ),
    ]
