# Generated by Django 3.1.4 on 2025-11-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0438_auto_20251128_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
