# Generated by Django 3.1.4 on 2025-11-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0439_payhistory_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconverthistory',
            name='pay1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_convert_from_payment', to='api.chiqim'),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='pay2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_convert_to_payment', to='api.kirim'),
        ),
    ]
