# Generated by Django 3.1.4 on 2025-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0440_auto_20251128_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconverthistory',
            name='currency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='from_cash_after',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='from_cash_before',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='summa2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='to_cash_after',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashconverthistory',
            name='to_cash_before',
            field=models.FloatField(default=0),
        ),
    ]
