# Generated by Django 3.1.4 on 2025-12-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0441_auto_20251128_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='currency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='summa',
            field=models.FloatField(default=0, null=True),
        ),
    ]
