# Generated by Django 3.1.4 on 2025-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0442_auto_20251201_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
