# Generated by Django 5.2.9 on 2025-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0445_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='valyuta',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
