# Generated by Django 5.2.9 on 2025-12-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0446_valyuta_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone1', models.CharField(blank=True, max_length=200, null=True)),
                ('phone2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productfilial',
            options={},
        ),
        migrations.AddField(
            model_name='payhistory',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wallet'),
        ),
        migrations.AddField(
            model_name='productbarcode',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='barcodes_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfilial',
            name='pricetypevaluta_prices_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productpricetype',
            unique_together={('product', 'valyuta', 'type')},
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['product'], name='api_product_product_65f997_idx'),
        ),
        migrations.AddIndex(
            model_name='productbarcode',
            index=models.Index(fields=['barcode'], name='api_product_barcode_7da484_idx'),
        ),
        migrations.AddIndex(
            model_name='productfilial',
            index=models.Index(fields=['filial'], name='api_product_filial__e7495b_idx'),
        ),
        migrations.AddIndex(
            model_name='productfilial',
            index=models.Index(fields=['name'], name='api_product_name_181d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='productfilial',
            index=models.Index(fields=['barcode'], name='api_product_barcode_383d87_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricetype',
            index=models.Index(fields=['product', 'valyuta'], name='api_product_product_3136c6_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricetype',
            index=models.Index(fields=['type'], name='api_product_type_id_9e8536_idx'),
        ),
        migrations.AddField(
            model_name='brand',
            name='main_valyuta',
            field=models.ForeignKey(blank=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.valyuta'),
        ),
    ]
