# Generated by Django 5.2.9 on 2025-12-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0447_brand_alter_productfilial_options_payhistory_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilial',
            name='bring_prices_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
