# Generated by Django 5.2.9 on 2026-01-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0448_productfilial_bring_prices_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
