# Generated by Django 5.2.9 on 2026-01-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0449_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliver_shops', to='api.deliver'),
        ),
    ]
