# Generated by Django 5.2.9 on 2026-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0451_paymenttypename_payhistory_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassamerge',
            name='is_naqd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymenttypename',
            name='is_naqd',
            field=models.BooleanField(default=True),
        ),
    ]
