# Generated by Django 5.2.9 on 2026-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0452_kassamerge_is_naqd_paymenttypename_is_naqd'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tab',
            field=models.CharField(blank=True, default='naqd-tab', max_length=20, null=True),
        ),
    ]
