# Generated by Django 5.2.9 on 2026-01-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0453_shop_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejachiqim',
            name='deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliver'),
        ),
    ]
