# Generated by Django 5.2.9 on 2026-01-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0454_rejachiqim_deliver'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTypePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0)),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pricetype')),
                ('recieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_percentages', to='api.recieve')),
            ],
        ),
    ]
