# Generated by Django 5.2.9 on 2026-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0455_pricetypepercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetype',
            name='is_dona',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='is_optom',
            field=models.BooleanField(default=False),
        ),
    ]
