# Generated by Django 5.2.9 on 2026-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0456_pricetype_is_dona_pricetype_is_optom'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneycirculation',
            name='for_qabul',
            field=models.BooleanField(default=False),
        ),
    ]
