# Generated by Django 5.2.9 on 2026-02-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0457_moneycirculation_for_qabul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieveexpanses',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.recieveexpansetypes'),
        ),
    ]
