# Generated by Django 5.2.9 on 2026-02-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0458_alter_recieveexpanses_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveexpanses',
            name='circulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moneycirculation'),
        ),
    ]
