from rest_framework.fields import ReadOnlyField
from rest_framework.routers import DefaultRouter
from .viewsets import *
from .mobilViewset import *

router = DefaultRouter()
# router.register('token', TokenViewset)
router.register('pricetype', PriceTypeSerializerViewset)
router.register('productpricetype', ProductPriceTypeSerializerViewset)
router.register('userprofile', UserProfileViewset)
router.register('filial', FilialViewset)
router.register('groups', GroupsViewset)
router.register('deliver', DeliverViewset)
router.register('products', Product_FilialViewset)
router.register('productfilial', ProductFilialViewsets)
router.register('recieve', RecieveViewset)
router.register('recieveitem', RecieveItemViewset)
router.register('faktura', FakturaViewset)
router.register('fakturaitem', FakturaItemViewset)
router.register('shop', ShopViewset)
router.register('cart', CartViewset)
router.register('debtor', DebtorViewset)
# router.register('debthistory', DebtHistoryViewset)
router.register('debt', DebtViewset)
router.register('payhistory', PayHistoryViewset)
router.register('cartdebt', CartDebtViewset)
router.register('returnproduct', ReturnProductViewset)
router.register('changeprice', ChangePriceViewset)
router.register('changepriceitem', ChangePriceItemViewset)
router.register('returnproducttodeliver', ReturnProductToDeliverViewset)
router.register('returnproducttodeliveritem', ReturnProductToDeliverItemViewset)
router.register('filial-expense', FilialExpenseViewSet)
router.register('filial-expense-category', FilialExpenseCategoryViewSet)
router.register('cashbox-receive', CashboxReceiveViewSet)
router.register('product-category', ProductCategoryViewset)
router.register('category', CategoryViewset)
router.register('payments_desktop', PaymentDebtorViewSet)
router.register('payments', PayCheckerViewSet)
router.register('payment-filter',PayCheckerStatus)
router.register('mcart', MCartViewset)
router.register('desktop_kassa_add', DesktopKassaViewSet)
router.register('desctopchiqim', DesctopChiqimViewset)
router.register('chiqim_turi', ChiqimTuriViewset)